import type { Chapter } from "../types";

export const arg1810: Chapter = {
  id: "arg1810",
  title: "Revolución de Mayo",
  accentColor: "rgba(184, 73, 15, 0.6)",
  reward: {
    name: "Escarapela de 1810",
    image: "escarapela",
    text: "Completaste la revolución de mayo de 1810 como hombre político. Completa la historia como pueblo para conseguir más partes de la escarapela",
  },
  screens: [
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "...",
      background: "viernes-18",
    },
    {
      type: "dialogue",
      character: "pena",
      speaker: "Nicolás Rodriguez Peña",
      text: "Hola! Mi nombre es Nicolás Rodríguez Peña, me dijeron que iba a venir a nuestra reunión.",
      background: "casa-pena-afuera",
    },
    {
      type: "dialogue",
      character: "pena",
      speaker: "Nicolás Rodriguez Peña",
      text: "Usted sabe, esta casa aquí atrás es mía, estamos reunidos muchos políticos aquí porque están pasando cosas importantes con respecto al actual virrey y con la idea de independencia.",
      background: "casa-pena-afuera",
    },
    {
      type: "dialogue",
      character: "pena",
      speaker: "Nicolás Rodriguez Peña",
      text: "De hecho, hace poco sucedió un hecho clave en España ¿Sabe de lo que estoy hablando?",
      background: "casa-pena-afuera",
    },
    {
      type: "question",
      character: "pena",
      speaker: "Nicolás Rodriguez Peña",
      text: "¿Sabe qué hecho importante sucedió en España?",
      background: "casa-pena-afuera",
      correct: { id: "arg1810-q5-correct", text: "Sí, la toma de Sevilla a manos de los franceses y la caída de la junta", help: "Exacto! Sevilla es una ciudad clave y esa junta era la que le daba poder al virrey de aquí" },
      distractors: [
        { id: "arg1810-q5-d1", text: "Una gran crisis financiera", help: "No precisamente, algo más relacionado a la guerra" },
        { id: "arg1810-q5-d2", text: "Quieren reconocer nuestro país como independiente", help: "No no, es más, aquí en America todavía están los ejercitos de la corona española para evitar cualquier tipo de intento de independecia" },
        { id: "arg1810-q5-d3", text: "Una invasión de Rusia", help: "Rusia está bastante lejos, no tiene ningún papel importante aquí" },
        { id: "arg1810-q5-d4", text: "Una guerra civil española", help: "Mmm... no no, algo relacionado a la guerra, sí, pero con otro país" },
      ],
    },
    {
      type: "dialogue",
      character: "pena",
      speaker: "Nicolás Rodriguez Peña",
      text: "Exacto! Con la caida de la junta, el virrey Cisneros perdió mucho apoyo y nosotros estamos viendo qué hacer al respecto. Por favor, pase.",
      background: "casa-pena-afuera",
    },
    {
      type: "dialogue",
      character: "pena",
      speaker: "Nicolás Rodriguez Peña",
      text: "Por favor, siéntase como en casa. Aquí estamos reunidos muchos políticos jóvenes con ansias de cambios revolucionarios.",
      background: "casa-pena-adentro",
    },
    {
      type: "dialogue",
      character: "belgrano",
      speaker: "Manuel Belgrano",
      text: "Estamos todos muy emocionados con la caída de la junta y nos alegra que haya venido a hablar de política con nosotros",
      background: "casa-pena-adentro",
    },
    {
      type: "dialogue",
      character: "belgrano",
      speaker: "Manuel Belgrano",
      text: "Una pregunta sobre estos sucesos ¿Sabe qué significa que la junta haya caído?",
      background: "casa-pena-adentro",
    },
    {
      type: "question",
      character: "belgrano",
      speaker: "Manuel Belgrano",
      text: "¿Sabe qué significa que la junta haya caído?",
      background: "casa-pena-adentro",
      correct: { id: "arg1810-q10-correct", text: "El actual virrey Cisneros fue designado por la junta de Sevilla, al estar tomada, ya no tiene legitimidad aquí", help: "Tal cual! Mucha gente aquí en el Virreynato del Río de la Plata (porque todavía no se llama Argentina) cree que debería retirarse" },
      distractors: [
        { id: "arg1810-q10-d1", text: "Que los ingleses pueden conquistarnos más fácilmente", help: "No no, los ingleses están con otros problemas allá en Europa, nuestros problemas son sólo con la Corona Española" },
        { id: "arg1810-q10-d2", text: "El virrey Saavedra asumirá en el poder", help: "No no, Saavedra es un político y militar de aquí, no es español. El virrey actual se llama Cisneros" },
        { id: "arg1810-q10-d3", text: "La independencia argentina", help: "Falta para eso! Por ahora se está hablando de revolución. La independencia llegará en 1816 recién" },
        { id: "arg1810-q10-d4", text: "Los españoles van a venir a atacarnos", help: "No! Están muy ocupados con las invasiones francesas." },
      ],
    },
    {
      type: "dialogue",
      character: "belgrano",
      speaker: "Manuel Belgrano",
      text: "¡Muy bien! Me alegro que esté tan comprometido con la causa. Bueno, esta va a ser una larga noche de discusiones políticas ¡Comencemos!",
      background: "casa-pena-adentro",
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "...",
      background: "sabado-19",
    },
    {
      type: "dialogue",
      character: "belgrano",
      speaker: "Manuel Belgrano",
      text: "!Uf! Estar toda la noche armando planes de revolución no es nada fácil",
      background: "casa-pena-adentro",
    },
    {
      type: "dialogue",
      character: "belgrano",
      speaker: "Manuel Belgrano",
      text: "Necesitamos consultar a las autoridades de inmediato ¿A quién crees que deberíamos acudir?",
      background: "casa-pena-adentro",
    },
    {
      type: "question",
      character: "belgrano",
      speaker: "Manuel Belgrano",
      text: "¿A qué autoridad política deberíamos acudir?",
      background: "casa-pena-adentro",
      correct: { id: "arg1810-q15-correct", text: "Al Alcalde Lezica", help: "Exacto! Belgrano junto a Saavedra acuden al Alcalde" },
      distractors: [
        { id: "arg1810-q15-d1", text: "Al presidente de Argentina", help: "No no, todavía no se llama Argentina, y la figura del presidente no existe, para eso faltan varios años" },
        { id: "arg1810-q15-d2", text: "A ninguna !Tomemos las armas¡", help: "Tranquilo, tanto Belgrano como Rodriguez Peña o Saavedra tienen mucha trayectoria política, prefieren hacer política antes que hacer una lucha armada" },
        { id: "arg1810-q15-d3", text: "A la Corona Española", help: "Nooo! Los españoles no quieren la revolución, mejor busquemos una autoridad más cercana" },
        { id: "arg1810-q15-d4", text: "Al parlamento latinoamericano", help: "No no, eso no existe. De hecho la gran mayoría de los países de America latina tienen autoridades de la corona española" },
      ],
    },
    {
      type: "dialogue",
      character: "belgrano",
      speaker: "Manuel Belgrano",
      text: "Excelente idea! Deberíamos ir con Saavedra a ver al alcalde. Por otro lado, Castelli debería hablar con el síndico procurador, Julián de Leyva",
      background: "casa-pena-adentro",
    },
    {
      type: "dialogue",
      character: "lezica",
      speaker: "Juan José Lezica",
      text: "Señores ¿En qué puedo ayudarlos?",
      background: "oficina-lezica",
    },
    {
      type: "question",
      character: "lezica",
      speaker: "Juan José Lezica",
      text: "¿Qué decidieron luego de su noche de discusión política?",
      background: "oficina-lezica",
      correct: { id: "arg1810-q18-correct", text: "Queremos un cabildo abierto", help: "Sí! De esa manera podrán discutir políticos y gente del pueblo sobre el futuro del virreynato" },
      distractors: [
        { id: "arg1810-q18-d1", text: "Queremos reforzar la autoridad del virrey Cisneros", help: "Nooo, el virrey Cisneros es de la corona española, la idea es destituirlo para que los políticos jóvenes de aquí asuman al gobierno" },
        { id: "arg1810-q18-d2", text: "Queremos empezar a llamarnos Argentina", help: "Nooo, eso recién en 1824 pasa. Todavía estamos en 1810." },
        { id: "arg1810-q18-d3", text: "Queremos irnos del país", help: "No! No estuvieron toda la noche discutiendo para irse del país, hay que hacer que la corona española deje de ser la autoridad" },
        { id: "arg1810-q18-d4", text: "No decidimos nada, necesitamos su ayuda", help: "No no, lo que se necesita es una posición activa de discusión. Hay que permitir el diálogo entre autoridades y pueblo de alguna manera" },
      ],
    },
    {
      type: "dialogue",
      character: "lezica",
      speaker: "Juan José Lezica",
      text: "Wow, realmente parecen convencidos de esto ¿Pero saben qué significa esto?",
      background: "oficina-lezica",
    },
    {
      type: "question",
      character: "lezica",
      speaker: "Juan José Lezica",
      text: "¿Saben qué significa un cabildo abierto?",
      background: "oficina-lezica",
      correct: { id: "arg1810-q20-correct", text: "Una reunión pública entre autoridades y pueblo para debatir temas de interés para la ciudadanía", help: "Sí, al fin una posibilidad de que la gente decida y no que todas las decisiones las tome la Corona Española" },
      distractors: [
        { id: "arg1810-q20-d1", text: "Dejar todas las puertas del cabildo sin llave para que todos puedan participar según deseen", help: "No! no es literal dejar el cabildo abierto. Decir Cabildo Abierto es simbólico" },
        { id: "arg1810-q20-d2", text: "Borrar la constitución y que toda la gente escriba lo que quiera", help: "Nooo, no existe una constitución todavía, además la discusión la llevan adelante ciertos políticos, no todo el mundo" },
        { id: "arg1810-q20-d3", text: "Llamar a elecciones a presidente", help: "No no, no existe la figura de presidente todavía" },
        { id: "arg1810-q20-d4", text: "Que se instaure el comunismo", help: "Noo! Esto va por otro lado, primero hay que decidir con el pueblo qué hacemos con el virrey ¿Cómo se podrá discutir algo así entre todos?" },
      ],
    },
    {
      type: "dialogue",
      character: "lezica",
      speaker: "Juan José Lezica",
      text: "Sí que están convencidos, tal vez sea el momento de comenzar algo nuevo !Una nueva era de políticos jóvenes de aproxima!",
      background: "oficina-lezica",
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "...",
      background: "domingo-20",
    },
    {
      type: "dialogue",
      character: "pena",
      speaker: "Nicolás Rodriguez Peña",
      text: "Señores, han pasado muchas cosas últimamente ¿Qué tal si nos ponemos al día?",
      background: "casa-pena-adentro",
    },
    {
      type: "dialogue",
      character: "belgrano",
      speaker: "Manuel Belgrano",
      text: "Nosotros fuimos a hablar con el Alcalde Lezica, Saavedra estaba ahí. Solicitamos que hable con Cisneros y llamen a un Cabildo Abierto",
      background: "casa-pena-adentro",
    },
    {
      type: "dialogue",
      character: "saavedra",
      speaker: "Cornelio Saavedra",
      text: "Sí, pero hay un pequeño detalle con Cisneros",
      background: "casa-pena-adentro",
    },
    {
      type: "question",
      character: "saavedra",
      speaker: "Cornelio Saavedra",
      text: "¿Qué hizo Cisneros cuando se le solicitó el Cabildo Abierto?",
      background: "casa-pena-adentro",
      correct: { id: "arg1810-q26-correct", text: "Cisneros se reunió con las fuerzas militares y se intentó preparar ante cualquier disturbio", help: "Bien! Eso significa que quiso prepararse para usar las fuerzas militares en su interés por si alguien intentaba hacer una revuelta" },
      distractors: [
        { id: "arg1810-q26-d1", text: "Renunció instantaneamente", help: "No! Cisneros tiene mucho interés en seguir siendo virrey, hizo otra cosa" },
        { id: "arg1810-q26-d2", text: "Accedió instantaneamente", help: "Ojalá hubiese sido tan fácil. No, de hecho Cisneros hizo algo para evitar cualquier revuelta" },
        { id: "arg1810-q26-d3", text: "Se fue a España", help: "No no, Cisneros sigue acá y no tiene intenciones de dejar el poder" },
        { id: "arg1810-q26-d4", text: "Prohibió a cualquier persona acercarse al Cabildo", help: "Noo! La autoridad de Cisneros está debilitada, no tiene el poder de hacer eso" },
      ],
    },
    {
      type: "dialogue",
      character: "saavedra",
      speaker: "Cornelio Saavedra",
      text: "Exacto! Quiso apelar a las fuerzas militares para usarlas en nuestra contra. Pero como yo soy el comandante del grupo militar más importante pude influenciar sobre la decisión",
      background: "casa-pena-adentro",
    },
    {
      type: "dialogue",
      character: "belgrano",
      speaker: "Manuel Belgrano",
      text: "Y como resultado ¡El cabildo abierto será realizado el 22 de Mayo!",
      background: "casa-pena-adentro",
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "...",
      background: "lunes-21",
    },
    {
      type: "dialogue",
      character: "donado",
      speaker: "Agustín José Donado",
      text: "Hola, soy Agustín Donado. Creo que no nos hemos presentado todavía, soy el encargado de la impresión de las invitaciones de las personas que vendrán mañana al cabildo abierto",
      background: "cabildo-vacio",
    },
    {
      type: "dialogue",
      character: "donado",
      speaker: "Agustín José Donado",
      text: "Hablando de invitaciones ¿Tienen idea quiénes serán invitados para mañana?",
      background: "cabildo-vacio",
    },
    {
      type: "question",
      character: "donado",
      speaker: "Agustín José Donado",
      text: "¿Quiénes recibirán invitaciones para el cabildo abierto de mañana?",
      background: "cabildo-vacio",
      correct: { id: "arg1810-q32-correct", text: "Necesitamos 450 invitaciones. Invitaremos a los principales vecinos y autoridades de la capital", help: "Exacto, se invitarán autoridades y vecinos" },
      distractors: [
        { id: "arg1810-q32-d1", text: "Necesitamos 500 invitaciones. Invitaremos a los políticos de todo el país", help: "Un poco menos de invitaciones, además los políticos invitados serán sólo de la capital" },
        { id: "arg1810-q32-d2", text: "Necesitamos 100 invitaciones. Estarán invitadas sólo las autoridades de la Corona Española", help: "No no, no queremos nada con la Corona Española en el cabildo abierto. Además, se esperan invitar muchas más personas que sólo 100" },
        { id: "arg1810-q32-d3", text: "Necesitamos 2000 invitaciones", help: "No! Esas son muchas invitaciones. Son muchas menos, además tenés que pensar quiénes estarán invitados" },
        { id: "arg1810-q32-d4", text: "No necesitamos invitaciones, el cabildo estará abierto para todos", help: "No no, se necesita un número concreto de personas, porque luego de discutir, se votará y esas personas tendrán que firmar" },
      ],
    },
    {
      type: "dialogue",
      character: "donado",
      speaker: "Agustín José Donado",
      text: "Excelente, las invitaciones serán enviadas. Nos vemos señor",
      background: "cabildo-vacio",
    },
    {
      type: "dialogue",
      character: "saavedra",
      speaker: "Cornelio Saavedra",
      text: "Buen día, veo que las invitaciones ya están en funcionamiento, por otro lado, tenemos un par de tareas de rutina hasta que…",
      background: "cabildo-vacio",
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "*ruido de muchedumbre",
      background: "cabildo-vacio",
    },
    {
      type: "dialogue",
      character: "saavedra",
      speaker: "Cornelio Saavedra",
      text: "Hay una gran movilización en las afueras del cabildo ¿Qué podrá ser?",
      background: "cabildo-lleno",
    },
    {
      type: "question",
      character: "saavedra",
      speaker: "Cornelio Saavedra",
      text: "¿Qué clase de movilización es esta?",
      background: "cabildo-lleno",
      correct: { id: "arg1810-q37-correct", text: "Es la LEGION INFERNAL. Encabezados por Domingo French y Antonio Luis Beruti", help: "Sí. La gente vino a apoyar el cabildo abierto, incluso muchos de ellos están armados" },
      distractors: [
        { id: "arg1810-q37-d1", text: "Son los ejercitos españoles", help: "No no, la multitud consiste en personas de aquí, no son españoles" },
        { id: "arg1810-q37-d2", text: "Es el desfile típico de esta época", help: "No! Este es un movimiento político" },
        { id: "arg1810-q37-d3", text: "Son los militares liderados por Cisneros", help: "No no, los militares siguen a Saavedra, Cisneros no tiene autoridad sobre ellos" },
        { id: "arg1810-q37-d4", text: "Son los ejercitos ingleses que vienen a atacarnos", help: "Nooo, los ingleses no tienen nada que ver acá, ellos están con sus propios problemas en algún lado lejos de aquí" },
      ],
    },
    {
      type: "dialogue",
      character: "saavedra",
      speaker: "Cornelio Saavedra",
      text: "Cierto! French y Beruti están ahí ¿Cuáles son sus demandas?",
      background: "cabildo-lleno",
    },
    {
      type: "question",
      character: "saavedra",
      speaker: "Cornelio Saavedra",
      text: "¿Cuáles son las demandas de la legión infernal?",
      background: "cabildo-lleno",
      correct: { id: "arg1810-q39-correct", text: "Están metiendo presión para que se realice el cabildo abierto y exigen la destitución inmediata de Cisneros", help: "Claro! La muchedumbre duda mucho de la palabra de los políticos y más de la palabra de los españoles, prefirieron tomar cartas en el asunto" },
      distractors: [
        { id: "arg1810-q39-d1", text: "La legión infernal está conformada por el pueblo y quieren que se cancele el cabildo abierto", help: "No no, es verdad que es el pueblo, pero ellos vienen a apoyar el cabildo abierto" },
        { id: "arg1810-q39-d2", text: "Vienen a defender a Cisneros para que se mantenga en el poder", help: "No! Estás personas están movilizadas para que Cisneros deje el poder de inmediato" },
        { id: "arg1810-q39-d3", text: "Es el pueblo, quieren que establezcamos una guerra contra la Corona Española", help: "No no! Nos interesan más nuestras propias cosas, no hay interés en entrar en guerra con España" },
        { id: "arg1810-q39-d4", text: "Sólo están reunidos aquí, no buscan nada en particular", help: "No! Ellos están aquí por algo muy importante!" },
      ],
    },
    {
      type: "dialogue",
      character: "saavedra",
      speaker: "Cornelio Saavedra",
      text: "Nos viene muy bien el apoyo al Cabildo Abierto. Pero no podemos destituir a Cisneros inmediatamente, necesitamos discutir eso en el Cabildo Abierto de mañana",
      background: "cabildo-lleno",
    },
    {
      type: "dialogue",
      character: "saavedra",
      speaker: "Cornelio Saavedra",
      text: "Intentaré calmas las aguas garantizando apoyo militar a sus reclamos",
      background: "cabildo-lleno",
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "...",
      background: "martes-22",
    },
    {
      type: "dialogue",
      character: "belgrano",
      speaker: "Manuel Belgrano",
      text: "Buen día señores, finalmente podemos darle inicio al Cabildo Abierto para decidir sobre la destitución o la permanencia del actual virrey Cisneros",
      background: "cabildo-abierto",
    },
    {
      type: "dialogue",
      character: "belgrano",
      speaker: "Manuel Belgrano",
      text: "Aquí presentes hay tanto representantes de la Corona Española como opositores al virrey. Obispo Lué ¿Quiere comenzar?",
      background: "cabildo-abierto",
    },
    {
      type: "dialogue",
      character: "obispo-lue",
      speaker: "Benito Lué y Riega",
      text: "Yo creo que mientras haya un español en América, los americanos le debemos obediencia, en este caso, le debemos obediencia a Cisneros",
      background: "cabildo-abierto",
    },
    {
      type: "dialogue",
      character: "castelli",
      speaker: "Juan José Castelli",
      text: "Yo no estoy de acuerdo ¿Qué debería opinar?",
      background: "cabildo-abierto",
    },
    {
      type: "question",
      character: "castelli",
      speaker: "Juan José Castelli",
      text: "¿Qué responde Castelli frente al obispo Lué?",
      background: "cabildo-abierto",
      correct: { id: "arg1810-q47-correct", text: "Que habiendo caducado el poder Real, la soberanía debía volver al pueblo que podía formar juntas de gobierno tanto en España como en América", help: "¡Perfecto! Castelli esta en el grupo de los que quieren que Cisneros deje el poder y se forme una junta de gobierno con gente del virreynato del río de la plata y no con españoles" },
      distractors: [
        { id: "arg1810-q47-d1", text: "Que la opinión del obispo tiene sentido y que decide defender al virrey Cisneros para que mantenga su posición", help: "Noo! Castelli es uno de los compormetidos para que Cisneros sea destituido" },
        { id: "arg1810-q47-d2", text: "Opina que Cisneros debe retirarse, pero que otro virrey español tome su lugar", help: "No no! Castelli forma parte del grupo que desea que la influencia de la Corona Española se reduzca o que incluso desaparezca" },
        { id: "arg1810-q47-d3", text: "Cree que lo mejor debería ser no opinar y dejar todo en manos de Belgrano", help: "Nooo, todos los presentes en el Cabildo Abierto son muy activos políticamente, todos quieren opinar y ser escuchados" },
        { id: "arg1810-q47-d4", text: "Le va a decir que no tiene autoridad para opinar", help: "No no, si bien Castelli opina diferente al obispo, debe dejarlo hablar y escucharlo" },
      ],
    },
    {
      type: "dialogue",
      character: "paso",
      speaker: "Juan José Paso",
      text: "¡Estoy de acuerdo con Castelli!",
      background: "cabildo-abierto",
    },
    {
      type: "question",
      character: "paso",
      speaker: "Juan José Paso",
      text: "¿Qué dice Paso para apoyar la opinión de Castelli?",
      background: "cabildo-abierto",
      correct: { id: "arg1810-q49-correct", text: "Opina que no había tiempo que perder y que había que formar inmediatamente una junta de gobierno sin Cisneros", help: "¡Sí! Una junta de gobierno con gente autóctona, sin Cisneros" },
      distractors: [
        { id: "arg1810-q49-d1", text: "Opina que hay que dejar entrar a la Legión Infernal para que opine", help: "No no, la idea del Cabildo es para que disctuan un selecto grupo de políticos, no todos" },
        { id: "arg1810-q49-d2", text: "Cree que lo mejor es levantar la sesión y tener tiempo para pensar", help: "Noo, Paso está muy convencido de lo que quiere, no está en sus planes perder el tiempo" },
        { id: "arg1810-q49-d3", text: "Opina que el poder lo deben tener los americanos, sólo hasta que el poder Real vuelva a tomar fuerza", help: "Eso no es así, la idea es establecer una junta sin la influencia de la Corona Española de manera definitiva" },
        { id: "arg1810-q49-d4", text: "No es necesario opinar, solamente votar al final de la sesión por la renuncia de Cisneros", help: "Paso tiene algo importante para decir, hay que decidir qué hacer si Cisneros deja el poder" },
      ],
    },
    {
      type: "dialogue",
      character: "belgrano",
      speaker: "Manuel Belgrano",
      text: "Bien, esta sesión va a ser muy larga, pero parece que la mayoría opina que Cisneros renuncie al poder",
      background: "cabildo-abierto",
    },
    {
      type: "dialogue",
      character: "belgrano",
      speaker: "Manuel Belgrano",
      text: "Mañana daremos a conocer la decisión al pueblo",
      background: "cabildo-abierto",
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "...",
      background: "miercoles-23",
    },
    {
      type: "dialogue",
      character: "belgrano",
      speaker: "Manuel Belgrano",
      text: "Bueno señores, la votación salió 155 a 69, triunfó la opción que exigía la deposición del virrey",
      background: "cabildo-abierto",
    },
    {
      type: "dialogue",
      character: "belgrano",
      speaker: "Manuel Belgrano",
      text: "Voy a garantizar que se corra la voz por todo el pueblo, porque esta es la voluntad popular",
      background: "cabildo-abierto",
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "...",
      background: "jueves-24",
    },
    {
      type: "dialogue",
      character: "pena",
      speaker: "Nicolás Rodriguez Peña",
      text: "Buen día, ayer se dio a conocer que la voluntad popular y la decisión del Cabildo Abierto fue la de sacar a Cisneros del poder",
      background: "casa-pena-adentro",
    },
    {
      type: "dialogue",
      character: "pena",
      speaker: "Nicolás Rodriguez Peña",
      text: "¿Te enteraste qué pasó luego?",
      background: "casa-pena-adentro",
    },
    {
      type: "question",
      character: "pena",
      speaker: "Nicolás Rodriguez Peña",
      text: "¿Qué pasó luego de avisar que Cisneros debía dejar el poder?",
      background: "casa-pena-adentro",
      correct: { id: "arg1810-q58-correct", text: "Un grupo del Cabildo formó una junta con Cisneros a la cabeza", help: "Lamentablemente, es cierto, si bien agregaron a la junta a algunos criollos, Cisneros sigue a la cabeza." },
      distractors: [
        { id: "arg1810-q58-d1", text: "Cisneros llamó al ejercito y está amenazando a sus opositores", help: "Cisneros aún tiene muchas influencias políticas aquí, no utilizó las armas en este caso" },
        { id: "arg1810-q58-d2", text: "La Corona Española envió otro representante", help: "En esa época las comunicaciones eran muy lentas, la Corona Española no llegó a enterarse de todo esto y enviar otro representante habría tomado mucho tiempo también" },
        { id: "arg1810-q58-d3", text: "Cisneros convenció a muchos políticos para que cambien su voto", help: "Cisneros decidió hacer otra cosa, pero no afectó la votación general" },
        { id: "arg1810-q58-d4", text: "Declaró la guerra con otro país", help: "No no, él sigue insistiendo en defender su posición de virrey, hizo otra cosa" },
      ],
    },
    {
      type: "dialogue",
      character: "pena",
      speaker: "Nicolás Rodriguez Peña",
      text: "Sí, estamos todo terriblemente enojados. Esta decisión traicionó la voluntad popular.",
      background: "casa-pena-adentro",
    },
    {
      type: "dialogue",
      character: "castelli",
      speaker: "Juan José Castelli",
      text: "¡Esto es inadmisible! Vamos a tomar cartas en el asunto",
      background: "casa-pena-adentro",
    },
    {
      type: "dialogue",
      character: "saavedra",
      speaker: "Cornelio Saavedra",
      text: "Iremos a visitar a Cisneros a su casa esta noche, iremos con un grupo de gente y lideraremos Castelli y yo",
      background: "casa-pena-adentro",
    },
    {
      type: "dialogue",
      character: "saavedra",
      speaker: "Cornelio Saavedra",
      text: "Vamos a convencerlo de que renuncie",
      background: "casa-pena-adentro",
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "...",
      background: "viernes-25",
    },
    {
      type: "dialogue",
      character: "saavedra",
      speaker: "Cornelio Saavedra",
      text: "Aquí estamos de vuelta en el Cabildo, frente a otra jornada de discusión",
      background: "cabildo-lleno",
    },
    {
      type: "dialogue",
      character: "saavedra",
      speaker: "Cornelio Saavedra",
      text: "Cisneros finalmente decidió dar un paso al costado. Además la junta formada ayer generó mucho rechazo en la población",
      background: "cabildo-lleno",
    },
    {
      type: "dialogue",
      character: "belgrano",
      speaker: "Manuel Belgrano",
      text: "Señores, la junta con Cisneros a la cabeza que se definió ayer no puede mantenerse",
      background: "cabildo-abierto",
    },
    {
      type: "dialogue",
      character: "paso",
      speaker: "Juan José Paso",
      text: "Sí, es necesario asignar otra junta de gobierno ¿Cómo podría formarse esa junta?",
      background: "cabildo-abierto",
    },
    {
      type: "question",
      character: "paso",
      speaker: "Juan José Paso",
      text: "¿Quién sería presidente de la junta y quiénes serían sus secretarios?",
      background: "cabildo-abierto",
      correct: { id: "arg1810-q68-correct", text: "Saavedra presidente. Moreno y Paso sus secretarios", help: "La influencia de Saavedra y su experiencia militar lo preparan como la opción más fuerte para ser presidente de la junta" },
      distractors: [
        { id: "arg1810-q68-d1", text: "No debería haber una junta, que el pueblo vote cada medida", help: "Eso sería un modelo totalmente diferente, la idea es formar un grupo que represente al pueblo" },
        { id: "arg1810-q68-d2", text: "Belgrano presidente", help: "Belgrano no tiene tanta influencia, es un buen candidato, pero no para presidente de junta. Además necesitamos también los secretarios" },
        { id: "arg1810-q68-d3", text: "Cisneros junto a otros dos representantes de la Corona", help: "Cisneros renunció anoche a su mandato y no tiene el apoyo del pueblo. Además queremos que la nueva junta sea con gente autóctona" },
        { id: "arg1810-q68-d4", text: "Saavedra debería ser el nuevo virrey", help: "Cuidado, Saavedra es un buen candidato, pero aquí se quiere formar una junta de gobierno, no un virreynato" },
      ],
    },
    {
      type: "dialogue",
      character: "paso",
      speaker: "Juan José Paso",
      text: "Estoy de acuerdo. Pero además debemos asignar 6 vocales ¿Quiénes podrán ser?",
      background: "cabildo-abierto",
    },
    {
      type: "question",
      character: "paso",
      speaker: "Juan José Paso",
      text: "¿Quiénes serán los 6 vocales?",
      background: "cabildo-abierto",
      correct: { id: "arg1810-q70-correct", text: "Belgrano, Castelli, Azcuénaga, Alberti, Larrea y Matheu", help: "Exacto! Son los hombres ideales por su trayectoria y sus ideales" },
      distractors: [
        { id: "arg1810-q70-d1", text: "San Martín, Rivadavia, Mitre, Roca, Illia y Perón", help: "Esos son personajes de épocas historicas muy diferente, no fueron contemporáneos" },
        { id: "arg1810-q70-d2", text: "Saavedra, Moreno y Paso", help: "Ellos ya están elegidos como presidente y secretarios, necesitamos elegir vocales ahora" },
        { id: "arg1810-q70-d3", text: "6 representantes de la legión infernal", help: "Ellos no forman parte del cabildo abierto, ellos están afuera representando el pueblo" },
        { id: "arg1810-q70-d4", text: "Opino que los primeros 6 en ofrecerse, sean los vocales", help: "Necesitamos definir los vocales por voto popular, elegir al azar podría constituir una junta muy débil" },
      ],
    },
    {
      type: "dialogue",
      character: "belgrano",
      speaker: "Manuel Belgrano",
      text: "Señores, este es un momento histórico para el virreynato del río de la Plata",
      background: "cabildo-abierto",
    },
    {
      type: "dialogue",
      character: "belgrano",
      speaker: "Manuel Belgrano",
      text: "Hagan correr la voz que de ahora en adelante el gobierno está en manos de una junta formada por criollos",
      background: "cabildo-abierto",
    },
    {
      type: "dialogue",
      character: "belgrano",
      speaker: "Manuel Belgrano",
      text: "¡Viva la revolución!",
      background: "cabildo-abierto",
    },
    {
      type: "dialogue",
      character: "pena",
      speaker: "Nicolás Rodriguez Peña",
      text: "Wow, estos sí que fueron días muy intensos",
      background: "casa-pena-afuera",
    },
    {
      type: "dialogue",
      character: "pena",
      speaker: "Nicolás Rodriguez Peña",
      text: "Queremos agradecerte tu participación durante todo este proceso",
      background: "casa-pena-afuera",
    },
    {
      type: "dialogue",
      character: "pena",
      speaker: "Nicolás Rodriguez Peña",
      text: "Por favor, toma esta escarapela en señal de agradecimiento ¡Muchas gracias!",
      background: "casa-pena-afuera",
    },
  ],
};
