import type { Chapter } from "../types";

export const guerra: Chapter = {
  id: "guerra",
  title: "Segunda Guerra Mundial",
  accentColor: "rgba(139, 40, 40, 0.6)",
  reward: {
    name: "Paloma de la paz",
    image: "paloma",
    text: "Completaste la Segunda Guerra Mundial. Recordar lo que pasó es la mejor manera de que no se repita. Selecciona cualquier otra época para seguir viajando por la historia",
  },
  screens: [
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "Una redacción de diarios, agosto de 1939",
      background: "redaccion",
    },
    {
      type: "dialogue",
      character: "corresponsal",
      speaker: "Corresponsal de guerra",
      text: "Bienvenido a la redacción. Soy corresponsal de guerra y usted será mi compañero en esta cobertura. Se vienen años muy duros, así que le voy a poner el contexto",
      background: "redaccion",
    },
    {
      type: "dialogue",
      character: "corresponsal",
      speaker: "Corresponsal de guerra",
      text: "Alemania salió de la Primera Guerra Mundial derrotada, con una economía arruinada y obligada a aceptar un tratado que muchos alemanes sintieron como una humillación",
      background: "redaccion",
    },
    {
      type: "question",
      character: "corresponsal",
      speaker: "Corresponsal de guerra",
      text: "¿Qué tratado puso fin formalmente a la Primera Guerra Mundial para Alemania?",
      background: "redaccion",
      correct: { id: "guerra-q4-correct", text: "El Tratado de Versalles, de 1919", help: "Exacto! Obligó a Alemania a pagar reparaciones y a reducir su ejército, y los nacionalistas lo usaron para ganar apoyo" },
      distractors: [
        { id: "guerra-q4-d1", text: "El Tratado de Tordesillas", help: "No no, ese fue de 1494 y dividió el mundo entre España y Portugal" },
        { id: "guerra-q4-d2", text: "El Pacto de Varsovia", help: "No, ese es de 1955, ya durante la Guerra Fría" },
        { id: "guerra-q4-d3", text: "La Paz de Westfalia", help: "No, esa es de 1648 y terminó otra guerra, la de los Treinta Años" },
        { id: "guerra-q4-d4", text: "El Tratado de Utrecht", help: "No, ese es de 1713 y terminó la guerra de sucesión española" },
      ],
    },
    {
      type: "dialogue",
      character: "corresponsal",
      speaker: "Corresponsal de guerra",
      text: "En 1933 Adolf Hitler llegó al poder y en pocos años convirtió a Alemania en una dictadura nazi: persiguió a sus opositores y a los judíos, y empezó a rearmarse",
      background: "redaccion",
    },
    {
      type: "dialogue",
      character: "corresponsal",
      speaker: "Corresponsal de guerra",
      text: "Y hace pocos días pasó algo que sorprendió al mundo. Alemania, que predicaba odio al comunismo, firmó un acuerdo con la Unión Soviética de Stalin",
      background: "redaccion",
    },
    {
      type: "question",
      character: "corresponsal",
      speaker: "Corresponsal de guerra",
      text: "¿Qué firmaron Alemania y la Unión Soviética en agosto de 1939?",
      background: "redaccion",
      correct: { id: "guerra-q7-correct", text: "Un pacto de no agresión que incluía el reparto secreto de Europa oriental", help: "Exacto! Se conoce como pacto Molotov-Ribbentrop, y le dio a Hitler tranquilidad para atacar a Polonia sin temer a los soviéticos" },
      distractors: [
        { id: "guerra-q7-d1", text: "Una alianza para atacar juntos a Inglaterra", help: "No, era un pacto de no agresión. Dos años después Alemania atacaría a la Unión Soviética" },
        { id: "guerra-q7-d2", text: "Un tratado de paz con Estados Unidos", help: "No no, Estados Unidos no participó en ese acuerdo" },
        { id: "guerra-q7-d3", text: "Una alianza militar con Japón", help: "No, el pacto con Japón e Italia es otro, de 1940" },
        { id: "guerra-q7-d4", text: "Un simple acuerdo comercial sin consecuencias", help: "No, tenía una parte secreta con un reparto territorial" },
      ],
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "Polonia, 1° de septiembre de 1939",
      background: "polonia-1939",
    },
    {
      type: "dialogue",
      character: "corresponsal",
      speaker: "Corresponsal de guerra",
      text: "Estoy en la frontera. Esta madrugada, las tropas alemanas invadieron Polonia con tanques y aviones. Dos días después, Inglaterra y Francia le declararon la guerra a Alemania",
      background: "polonia-1939",
    },
    {
      type: "question",
      character: "corresponsal",
      speaker: "Corresponsal de guerra",
      text: "¿Qué hecho marca el comienzo de la guerra en Europa?",
      background: "polonia-1939",
      correct: { id: "guerra-q10-correct", text: "La invasión alemana a Polonia, el 1° de septiembre de 1939", help: "Exacto! Alemania usó la \"guerra relámpago\" (Blitzkrieg), con tanques y aviones. El 17 de septiembre la Unión Soviética también invadió Polonia por el este" },
      distractors: [
        { id: "guerra-q10-d1", text: "El ataque japonés a Pearl Harbor", help: "No, eso fue más tarde, en diciembre de 1941" },
        { id: "guerra-q10-d2", text: "La invasión alemana a Francia", help: "No, Francia fue atacada en mayo de 1940, después de Polonia" },
        { id: "guerra-q10-d3", text: "El bombardeo de Londres", help: "No, el bombardeo masivo de Londres empezó en 1940" },
        { id: "guerra-q10-d4", text: "La caída del Muro de Berlín", help: "Nooo, eso pasó en 1989" },
      ],
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "Francia, junio de 1940",
      background: "londres-1940",
    },
    {
      type: "dialogue",
      character: "corresponsal",
      speaker: "Corresponsal de guerra",
      text: "Los alemanes avanzaron muy rápido: en pocas semanas ocuparon Holanda, Bélgica y Francia, que firmó un armisticio el 22 de junio. Antes, casi 340.000 soldados aliados tuvieron que escapar por el mar desde las playas de Dunkerque",
      background: "londres-1940",
    },
    {
      type: "question",
      character: "corresponsal",
      speaker: "Corresponsal de guerra",
      text: "¿Qué ocurrió en Dunkerque?",
      background: "londres-1940",
      correct: { id: "guerra-q13-correct", text: "Más de 300.000 soldados aliados fueron evacuados por mar hacia Inglaterra", help: "Exacto! No fue una victoria, pero permitió salvar a un ejército que más tarde seguiría peleando" },
      distractors: [
        { id: "guerra-q13-d1", text: "Inglaterra se rindió ante Alemania", help: "Nooo, Inglaterra siguió peleando" },
        { id: "guerra-q13-d2", text: "Los aliados desembarcaron y liberaron Francia", help: "No, eso fue en 1944, con el Día D" },
        { id: "guerra-q13-d3", text: "Estados Unidos entró en la guerra", help: "No, todavía faltaba más de un año para eso" },
        { id: "guerra-q13-d4", text: "Se firmó la paz entre todos los países", help: "No no, la guerra recién estaba empezando" },
      ],
    },
    {
      type: "dialogue",
      character: "churchill",
      speaker: "Winston Churchill",
      text: "Soy Winston Churchill, primer ministro británico desde mayo. No ofrezco más que sangre, esfuerzo, lágrimas y sudor. Inglaterra no se rendirá jamás",
      background: "londres-1940",
    },
    {
      type: "dialogue",
      character: "churchill",
      speaker: "Winston Churchill",
      text: "Hitler quiere invadirnos, pero antes necesita dominar el cielo. Estas semanas, de julio a octubre, serán decisivas",
      background: "londres-1940",
    },
    {
      type: "question",
      character: "churchill",
      speaker: "Winston Churchill",
      text: "¿Por qué fracasó la Luftwaffe alemana en la Batalla de Inglaterra?",
      background: "londres-1940",
      correct: { id: "guerra-q16-correct", text: "Porque la fuerza aérea británica (RAF) resistió, con ayuda del radar, y los alemanes no lograron controlar el cielo", help: "Exacto! Sin superioridad aérea, Alemania no pudo invadir las islas. Igual, Londres sufrió meses de bombardeos" },
      distractors: [
        { id: "guerra-q16-d1", text: "Porque Alemania no tenía aviones", help: "No no, tenía muchísimos aviones, pero no alcanzaron" },
        { id: "guerra-q16-d2", text: "Porque Estados Unidos ya había entrado en la guerra", help: "No, todavía no había entrado" },
        { id: "guerra-q16-d3", text: "Porque Inglaterra se rindió", help: "Nooo, resistió" },
        { id: "guerra-q16-d4", text: "Por una gran tormenta", help: "No, el clima no fue la razón" },
      ],
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "Buenos Aires, 1940",
      background: "buenos-aires-1945",
    },
    {
      type: "dialogue",
      character: "corresponsal",
      speaker: "Corresponsal de guerra",
      text: "Acá, en Argentina, el gobierno declaró la neutralidad. Pero la guerra llega igual: en 1940 un submarino alemán hundió el barco argentino Uruguay, y años después otros barcos corrieron la misma suerte",
      background: "buenos-aires-1945",
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "Frente oriental, 22 de junio de 1941",
      background: "frente-ruso",
    },
    {
      type: "dialogue",
      character: "corresponsal",
      speaker: "Corresponsal de guerra",
      text: "A pesar del pacto firmado, Alemania acaba de invadir la Unión Soviética. Es el ataque más grande de la historia, con millones de soldados. Se lo llamó Operación Barbarroja",
      background: "frente-ruso",
    },
    {
      type: "question",
      character: "corresponsal",
      speaker: "Corresponsal de guerra",
      text: "¿Qué ocurrió el 22 de junio de 1941?",
      background: "frente-ruso",
      correct: { id: "guerra-q21-correct", text: "Alemania invadió la Unión Soviética en la Operación Barbarroja", help: "Exacto! La guerra pasó a ser mundial y el frente oriental fue el más sangriento de todos" },
      distractors: [
        { id: "guerra-q21-d1", text: "Japón atacó Pearl Harbor", help: "No, ese ataque fue el 7 de diciembre de 1941" },
        { id: "guerra-q21-d2", text: "Los aliados desembarcaron en Normandía", help: "No, eso fue el 6 de junio de 1944" },
        { id: "guerra-q21-d3", text: "Alemania se rindió", help: "No no, Alemania se rindió en 1945" },
        { id: "guerra-q21-d4", text: "Inglaterra firmó la paz con Alemania", help: "Nooo, Inglaterra siguió en la guerra" },
      ],
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "Pearl Harbor, Hawái, 8 de diciembre de 1941",
      background: "pearl-harbor",
    },
    {
      type: "dialogue",
      character: "corresponsal",
      speaker: "Corresponsal de guerra",
      text: "Ayer por la mañana aviones japoneses atacaron por sorpresa la base naval de Pearl Harbor y hundieron o dañaron muchos buques estadounidenses",
      background: "pearl-harbor",
    },
    {
      type: "dialogue",
      character: "roosevelt",
      speaker: "Franklin Roosevelt",
      text: "Soy Franklin Roosevelt, presidente de Estados Unidos. Ayer fue una fecha que vivirá en la infamia. Le pido al Congreso que declare el estado de guerra con Japón",
      background: "pearl-harbor",
    },
    {
      type: "question",
      character: "roosevelt",
      speaker: "Franklin Roosevelt",
      text: "¿Qué hecho llevó a Estados Unidos a entrar en la Segunda Guerra Mundial?",
      background: "pearl-harbor",
      correct: { id: "guerra-q25-correct", text: "El ataque japonés a Pearl Harbor", help: "Exacto! Pocos días después Alemania e Italia le declararon la guerra a Estados Unidos, y la guerra quedó dividida entre Aliados y Eje" },
      distractors: [
        { id: "guerra-q25-d1", text: "La caída de Francia", help: "No, eso fue en 1940 y Estados Unidos todavía era neutral" },
        { id: "guerra-q25-d2", text: "La invasión alemana a Polonia", help: "No, eso fue en 1939" },
        { id: "guerra-q25-d3", text: "El bombardeo alemán a Londres", help: "No, Estados Unidos ayudó a Inglaterra pero sin declarar la guerra" },
        { id: "guerra-q25-d4", text: "La invasión soviética a Finlandia", help: "No, eso no lo involucró en la guerra" },
      ],
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "Europa ocupada, 1942",
      background: "berlin-1945",
    },
    {
      type: "dialogue",
      character: "corresponsal",
      speaker: "Corresponsal de guerra",
      text: "Tengo que contarle algo muy grave. Durante estos años el régimen nazi persiguió, encerró y asesinó de forma sistemática a millones de personas",
      background: "berlin-1945",
    },
    {
      type: "dialogue",
      character: "corresponsal",
      speaker: "Corresponsal de guerra",
      text: "En enero de 1942, funcionarios nazis se reunieron en Wannsee para organizar el exterminio de los judíos de Europa. Murieron unos seis millones. También fueron perseguidos y asesinados gitanos, personas con discapacidad, prisioneros soviéticos y opositores políticos",
      background: "berlin-1945",
    },
    {
      type: "question",
      character: "corresponsal",
      speaker: "Corresponsal de guerra",
      text: "¿Cómo se llama el genocidio de unos seis millones de judíos europeos cometido por el régimen nazi?",
      background: "berlin-1945",
      correct: { id: "guerra-q29-correct", text: "El Holocausto, también llamado Shoá", help: "Así es. Es uno de los crímenes más terribles de la historia, y por eso es tan importante recordarlo" },
      distractors: [
        { id: "guerra-q29-d1", text: "La Gran Purga", help: "No, ese fue un período de represión en la Unión Soviética en la década de 1930" },
        { id: "guerra-q29-d2", text: "El Blitz", help: "No, el Blitz fue el bombardeo alemán sobre ciudades inglesas" },
        { id: "guerra-q29-d3", text: "La Noche de los cuchillos largos", help: "No, ese fue un episodio de 1934 dentro del propio partido nazi" },
        { id: "guerra-q29-d4", text: "La Gran Depresión", help: "No, esa fue una crisis económica de 1929" },
      ],
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "Stalingrado, invierno de 1942-1943",
      background: "frente-ruso",
    },
    {
      type: "dialogue",
      character: "corresponsal",
      speaker: "Corresponsal de guerra",
      text: "Desde agosto, alemanes y soviéticos pelean casa por casa en Stalingrado. El invierno es durísimo y el ejército alemán quedó rodeado",
      background: "frente-ruso",
    },
    {
      type: "question",
      character: "corresponsal",
      speaker: "Corresponsal de guerra",
      text: "¿Por qué fue tan importante la batalla de Stalingrado?",
      background: "frente-ruso",
      correct: { id: "guerra-q32-correct", text: "Porque la derrota y rendición del VI Ejército alemán, en febrero de 1943, marcó un punto de inflexión en el frente oriental", help: "Exacto! A partir de ahí el Ejército Rojo avanzó hacia el oeste y Alemania ya no volvió a ganar la iniciativa" },
      distractors: [
        { id: "guerra-q32-d1", text: "Porque fue la primera victoria alemana de la guerra", help: "No no, fue una gran derrota alemana" },
        { id: "guerra-q32-d2", text: "Porque allí se firmó la paz", help: "No, la guerra siguió más de dos años" },
        { id: "guerra-q32-d3", text: "Porque allí desembarcaron los aliados", help: "No, eso fue en Normandía" },
        { id: "guerra-q32-d4", text: "Porque fue una batalla naval", help: "No, fue una batalla terrestre en una ciudad" },
      ],
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "Normandía, Francia, 6 de junio de 1944",
      background: "normandia",
    },
    {
      type: "dialogue",
      character: "eisenhower",
      speaker: "Dwight Eisenhower",
      text: "Soy el general Dwight Eisenhower, comandante supremo aliado. Hoy, con miles de barcos y aviones, comienza la operación para liberar Francia y llegar hasta Alemania",
      background: "normandia",
    },
    {
      type: "question",
      character: "eisenhower",
      speaker: "Dwight Eisenhower",
      text: "¿Qué fue el Día D?",
      background: "normandia",
      correct: { id: "guerra-q35-correct", text: "El desembarco aliado en las playas de Normandía, el 6 de junio de 1944", help: "Exacto! Fue la mayor operación anfibia de la historia, y abrió un segundo frente contra Alemania en Europa occidental" },
      distractors: [
        { id: "guerra-q35-d1", text: "El bombardeo atómico a Hiroshima", help: "No, eso fue en agosto de 1945 y en Japón" },
        { id: "guerra-q35-d2", text: "La rendición de Alemania", help: "No, eso fue casi un año después, en mayo de 1945" },
        { id: "guerra-q35-d3", text: "El ataque a Pearl Harbor", help: "No, ese fue en diciembre de 1941" },
        { id: "guerra-q35-d4", text: "La liberación de Auschwitz", help: "No, el ejército soviético liberó Auschwitz en enero de 1945" },
      ],
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "Buenos Aires, 27 de marzo de 1945",
      background: "buenos-aires-1945",
    },
    {
      type: "dialogue",
      character: "corresponsal",
      speaker: "Corresponsal de guerra",
      text: "Esta es una noticia importante para nosotros. Argentina declaró la guerra a Alemania y a Japón, cuando la guerra ya estaba casi decidida",
      background: "buenos-aires-1945",
    },
    {
      type: "question",
      character: "corresponsal",
      speaker: "Corresponsal de guerra",
      text: "¿Qué hizo Argentina durante casi toda la Segunda Guerra Mundial?",
      background: "buenos-aires-1945",
      correct: { id: "guerra-q38-correct", text: "Se mantuvo neutral y declaró la guerra al Eje recién en marzo de 1945", help: "Exacto! Hubo mucha presión de los Aliados. Además, después de la guerra algunos criminales nazis encontraron refugio en Argentina" },
      distractors: [
        { id: "guerra-q38-d1", text: "Declaró la guerra a Alemania en 1939", help: "No, mantuvo la neutralidad hasta 1945" },
        { id: "guerra-q38-d2", text: "Fue aliada de Japón desde el principio", help: "No, nunca fue aliada de Japón" },
        { id: "guerra-q38-d3", text: "Fue invadida por tropas alemanas", help: "Nooo, la guerra no llegó a su territorio" },
        { id: "guerra-q38-d4", text: "Envió un ejército a pelear a Normandía", help: "No, no envió tropas a combatir" },
      ],
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "Berlín, mayo de 1945",
      background: "berlin-1945",
    },
    {
      type: "dialogue",
      character: "corresponsal",
      speaker: "Corresponsal de guerra",
      text: "Berlín está en ruinas. Las tropas soviéticas entraron en la ciudad y Hitler se suicidó el 30 de abril. Pocos días después Alemania firmó su rendición incondicional",
      background: "berlin-1945",
    },
    {
      type: "question",
      character: "corresponsal",
      speaker: "Corresponsal de guerra",
      text: "¿Qué día se celebra la victoria aliada en Europa?",
      background: "berlin-1945",
      correct: { id: "guerra-q41-correct", text: "El 8 de mayo de 1945", help: "Exacto! Se conoce como el Día de la Victoria en Europa (V-E Day)" },
      distractors: [
        { id: "guerra-q41-d1", text: "El 6 de junio de 1944", help: "No, esa fecha es la del desembarco en Normandía" },
        { id: "guerra-q41-d2", text: "El 15 de agosto de 1945", help: "No, esa fecha está relacionada con la rendición de Japón" },
        { id: "guerra-q41-d3", text: "El 1° de septiembre de 1939", help: "No, esa fecha es la del comienzo de la guerra" },
        { id: "guerra-q41-d4", text: "El 7 de diciembre de 1941", help: "No, esa fecha es la del ataque a Pearl Harbor" },
      ],
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "Hiroshima, Japón, agosto de 1945",
      background: "hiroshima",
    },
    {
      type: "dialogue",
      character: "corresponsal",
      speaker: "Corresponsal de guerra",
      text: "En Europa terminó la guerra, pero Japón siguió peleando. Estados Unidos tenía un arma nueva y devastadora, y decidió usarla",
      background: "hiroshima",
    },
    {
      type: "question",
      character: "corresponsal",
      speaker: "Corresponsal de guerra",
      text: "¿Dónde y cuándo se lanzó la primera bomba atómica usada en una guerra?",
      background: "hiroshima",
      correct: { id: "guerra-q44-correct", text: "En Hiroshima, el 6 de agosto de 1945", help: "Exacto! Tres días después se lanzó otra sobre Nagasaki. Decenas de miles de personas murieron de inmediato y muchísimas más en los meses siguientes" },
      distractors: [
        { id: "guerra-q44-d1", text: "En Nagasaki, el 6 de agosto de 1945", help: "No, Nagasaki fue la segunda bomba, el 9 de agosto" },
        { id: "guerra-q44-d2", text: "En Tokio, en 1944", help: "No, Tokio fue bombardeada con bombas convencionales, no atómicas" },
        { id: "guerra-q44-d3", text: "En Berlín, en mayo de 1945", help: "No, Alemania nunca sufrió un ataque atómico" },
        { id: "guerra-q44-d4", text: "En Pearl Harbor, en 1941", help: "No, Pearl Harbor fue atacada por Japón con aviones, no con bombas atómicas" },
      ],
    },
    {
      type: "dialogue",
      character: "corresponsal",
      speaker: "Corresponsal de guerra",
      text: "Japón anunció su rendición el 15 de agosto y la firmó el 2 de septiembre de 1945. Así terminó la guerra más destructiva de la historia, que dejó decenas de millones de muertos, la mayoría civiles",
      background: "hiroshima",
    },
    {
      type: "dialogue",
      character: "corresponsal",
      speaker: "Corresponsal de guerra",
      text: "Todavía hoy se debate si era necesario usar las bombas atómicas. Lo que nadie discute es que tanto dolor no debería repetirse jamás",
      background: "hiroshima",
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "San Francisco, octubre de 1945",
      background: "redaccion",
    },
    {
      type: "dialogue",
      character: "corresponsal",
      speaker: "Corresponsal de guerra",
      text: "Para evitar nuevas guerras, se fundó una organización internacional de países. Su carta fue firmada en San Francisco en junio y entró en vigor en octubre",
      background: "redaccion",
    },
    {
      type: "question",
      character: "corresponsal",
      speaker: "Corresponsal de guerra",
      text: "¿Qué organización se creó en 1945 para promover la paz entre los países?",
      background: "redaccion",
      correct: { id: "guerra-q49-correct", text: "Las Naciones Unidas (ONU)", help: "Exacto! Argentina fue uno de sus países fundadores. También se aprobó, en 1948, la Declaración Universal de los Derechos Humanos" },
      distractors: [
        { id: "guerra-q49-d1", text: "La Liga de las Naciones", help: "No, esa se creó después de la Primera Guerra, en 1919, y no logró evitar la Segunda" },
        { id: "guerra-q49-d2", text: "La OTAN", help: "No, esa alianza militar se creó en 1949" },
        { id: "guerra-q49-d3", text: "La Unión Europea", help: "No, esa unión llegó mucho más tarde" },
        { id: "guerra-q49-d4", text: "La Cruz Roja", help: "No, la Cruz Roja es de 1863" },
      ],
    },
    {
      type: "dialogue",
      character: "corresponsal",
      speaker: "Corresponsal de guerra",
      text: "Gracias por acompañarme en esta cobertura. Tome esta paloma como símbolo de la paz. Hay que recordar la historia para que no se repita ¡Hasta la próxima!",
      background: "redaccion",
    },
  ],
};
