import type { Chapter } from "../types";

export const industrial: Chapter = {
  id: "industrial",
  title: "Revolución industrial",
  accentColor: "rgba(96, 110, 128, 0.6)",
  reward: {
    name: "Engranaje de la Revolución industrial",
    image: "engranaje",
    text: "Completaste la revolución industrial. Selecciona cualquier otra época para seguir viajando por la historia",
  },
  screens: [
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "Inglaterra, alrededor de 1760",
      background: "taller-rural",
    },
    {
      type: "dialogue",
      character: "obrero",
      speaker: "Obrero textil",
      text: "Bienvenido. Acá, en los pueblos del norte de Inglaterra, las familias hilan y tejen en sus propias casas. Un comerciante les trae la lana o el algodón y después pasa a buscar la tela",
      background: "taller-rural",
    },
    {
      type: "dialogue",
      character: "obrero",
      speaker: "Obrero textil",
      text: "Es un trabajo lento, hecho a mano. Pero muy pronto todo esto va a cambiar, y Inglaterra será la primera en vivirlo",
      background: "taller-rural",
    },
    {
      type: "question",
      character: "obrero",
      speaker: "Obrero textil",
      text: "¿Por qué la industrialización empezó en Inglaterra?",
      background: "taller-rural",
      correct: { id: "industrial-q4-correct", text: "Tenía carbón y hierro cerca, capitales del comercio colonial, mano de obra liberada del campo y una gran flota", help: "Exacto! Todos esos factores juntos hicieron de Inglaterra el lugar ideal para que empezara la industrialización" },
      distractors: [
        { id: "industrial-q4-d1", text: "Porque no tenía agricultura y toda su gente vivía en ciudades", help: "No no, al contrario: los cambios en la agricultura dejaron sin trabajo en el campo a mucha gente que fue a buscarlo a las ciudades" },
        { id: "industrial-q4-d2", text: "Porque era gobernada por Napoleón", help: "Nooo, Napoleón era francés y enemigo de Inglaterra" },
        { id: "industrial-q4-d3", text: "Porque fue el primer país en inventar la imprenta", help: "No, la imprenta se inventó en el siglo XV y en Alemania" },
        { id: "industrial-q4-d4", text: "Porque era el único país con ríos", help: "No, hay ríos en todos lados. Lo importante fue la combinación de recursos, capital y mano de obra" },
      ],
    },
    {
      type: "dialogue",
      character: "obrero",
      speaker: "Obrero textil",
      text: "Los comerciantes necesitaban más hilo y más rápido, así que los inventores se pusieron a trabajar. ¿Sabe quién fue James Hargreaves?",
      background: "taller-rural",
    },
    {
      type: "question",
      character: "obrero",
      speaker: "Obrero textil",
      text: "¿Qué inventó James Hargreaves alrededor de 1764?",
      background: "taller-rural",
      correct: { id: "industrial-q6-correct", text: "La spinning jenny, una máquina que hilaba varios hilos a la vez", help: "Exacto! Con una sola persona se podía hilar mucho más que antes, y eso hizo crecer la producción de tela" },
      distractors: [
        { id: "industrial-q6-d1", text: "La locomotora a vapor", help: "No, la locomotora llega bastante después, en el siglo XIX" },
        { id: "industrial-q6-d2", text: "La máquina de vapor", help: "No no, esa fue mejorada por James Watt. Ya lo vamos a conocer" },
        { id: "industrial-q6-d3", text: "El telar mecánico", help: "Casi! El telar mecánico lo inventó Edmund Cartwright hacia 1785" },
        { id: "industrial-q6-d4", text: "La desmotadora de algodón", help: "No, esa la inventó el norteamericano Eli Whitney en 1793" },
      ],
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "Cromford, 1771",
      background: "fabrica-textil",
    },
    {
      type: "dialogue",
      character: "arkwright",
      speaker: "Richard Arkwright",
      text: "Soy Richard Arkwright. Instalé esta fábrica junto al río y una gran rueda de agua mueve todas las máquinas de hilar",
      background: "fabrica-textil",
    },
    {
      type: "dialogue",
      character: "arkwright",
      speaker: "Richard Arkwright",
      text: "Acá trabajan cientos de personas, incluidos muchos niños, con horarios fijos que marca la campana. Es una forma de trabajar totalmente nueva",
      background: "fabrica-textil",
    },
    {
      type: "question",
      character: "arkwright",
      speaker: "Richard Arkwright",
      text: "¿Qué cambió con la aparición de la fábrica?",
      background: "fabrica-textil",
      correct: { id: "industrial-q10-correct", text: "Los trabajadores dejaron de trabajar en casa y pasaron a hacerlo en un lugar común, con horarios y bajo las órdenes de un patrón", help: "Exacto! Así nació la fábrica moderna y con ella una nueva forma de vida para los trabajadores" },
      distractors: [
        { id: "industrial-q10-d1", text: "Los trabajadores pasaron a ser dueños de las máquinas", help: "No, las máquinas eran muy caras y eran propiedad del dueño de la fábrica" },
        { id: "industrial-q10-d2", text: "Se terminó la necesidad de trabajar", help: "Nooo, al contrario, había que trabajar muchas horas" },
        { id: "industrial-q10-d3", text: "Cada uno elegía su propio horario", help: "No, los horarios los fijaba el dueño y se controlaban con campana" },
        { id: "industrial-q10-d4", text: "Se prohibió el trabajo infantil", help: "No, recién décadas más tarde se empezaron a poner límites" },
      ],
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "Birmingham, 1776",
      background: "fabrica-textil",
    },
    {
      type: "dialogue",
      character: "watt",
      speaker: "James Watt",
      text: "Soy James Watt. Mejoré la máquina de vapor agregándole un condensador separado, y con mi socio Matthew Boulton ya empezamos a venderlas",
      background: "fabrica-textil",
    },
    {
      type: "question",
      character: "watt",
      speaker: "James Watt",
      text: "¿Qué ventaja dio la máquina de vapor a la industria?",
      background: "fabrica-textil",
      correct: { id: "industrial-q13-correct", text: "Permitió instalar fábricas lejos de los ríos y mover las máquinas quemando carbón", help: "Exacto! Ya no hacía falta depender de la fuerza del agua, y el carbón se volvió fundamental" },
      distractors: [
        { id: "industrial-q13-d1", text: "Funcionaba con energía solar", help: "Nooo, funcionaba quemando carbón para producir vapor" },
        { id: "industrial-q13-d2", text: "Usaba petróleo", help: "No, el petróleo se usó mucho después" },
        { id: "industrial-q13-d3", text: "Servía únicamente para mover barcos", help: "No, primero se usó en minas y fábricas. Los barcos a vapor llegaron más tarde" },
        { id: "industrial-q13-d4", text: "La movían caballos", help: "No no, justamente reemplazaba la fuerza de los animales" },
      ],
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "Una mina de carbón, hacia 1840",
      background: "mina-carbon",
    },
    {
      type: "dialogue",
      character: "obrero",
      speaker: "Obrero textil",
      text: "Esta es la mina que alimenta con carbón a las fábricas y a las máquinas de vapor. Mire cuántos trabajan acá abajo",
      background: "mina-carbon",
    },
    {
      type: "question",
      character: "obrero",
      speaker: "Obrero textil",
      text: "¿Quiénes trabajaban en las minas y las fábricas?",
      background: "mina-carbon",
      correct: { id: "industrial-q16-correct", text: "Hombres, mujeres y también niños, con jornadas de 12 horas o más", help: "Exacto! Eran trabajos duros y peligrosos. Recién en 1842 una ley prohibió que mujeres y niños muy pequeños trabajaran bajo tierra" },
      distractors: [
        { id: "industrial-q16-d1", text: "Solamente hombres adultos con jornadas de 6 horas", help: "No no, las jornadas eran mucho más largas y trabajaba toda la familia" },
        { id: "industrial-q16-d2", text: "Solamente esclavos traídos de África", help: "No, los trabajadores eran ingleses, irlandeses y de otras zonas. La esclavitud estaba en las plantaciones de otras regiones" },
        { id: "industrial-q16-d3", text: "Solamente técnicos con vacaciones pagas", help: "Nooo, las vacaciones pagas llegaron mucho más tarde" },
        { id: "industrial-q16-d4", text: "Solamente máquinas, sin personas", help: "No, las máquinas necesitaban muchísimas personas para funcionar" },
      ],
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "Nottinghamshire, 1811",
      background: "fabrica-textil",
    },
    {
      type: "dialogue",
      character: "obrero",
      speaker: "Obrero textil",
      text: "Anoche un grupo de tejedores entró a un taller y destrozó los telares. Dicen que los lidera un tal \"Ned Ludd\", aunque quizás ni exista",
      background: "fabrica-textil",
    },
    {
      type: "question",
      character: "obrero",
      speaker: "Obrero textil",
      text: "¿Por qué los luditas destruían las máquinas?",
      background: "fabrica-textil",
      correct: { id: "industrial-q19-correct", text: "Porque temían quedarse sin trabajo y que les bajaran los salarios", help: "Exacto! Para ellos las máquinas eran el símbolo de lo que les quitaba su oficio. El gobierno respondió con tropas y con la pena de muerte para quien rompiera máquinas" },
      distractors: [
        { id: "industrial-q19-d1", text: "Porque estaban en contra del rey", help: "No, su problema era laboral, no político" },
        { id: "industrial-q19-d2", text: "Porque querían reemplazarlas por otras mejores", help: "No no, querían que no las usaran para pagar peores sueldos" },
        { id: "industrial-q19-d3", text: "Porque contaminaban el aire de las ciudades", help: "No, esa no era su preocupación principal en esa época" },
        { id: "industrial-q19-d4", text: "Por diversión", help: "Nooo, era un movimiento muy serio y muy reprimido" },
      ],
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "Manchester, 1819",
      background: "calle-manchester",
    },
    {
      type: "dialogue",
      character: "obrero",
      speaker: "Obrero textil",
      text: "Hoy se juntaron decenas de miles de personas en el campo de San Pedro para pedir cambios políticos. Pero la caballería cargó contra la multitud: murieron unas dieciocho",
      background: "calle-manchester",
    },
    {
      type: "question",
      character: "obrero",
      speaker: "Obrero textil",
      text: "¿Qué reclamaban los trabajadores en la matanza de Peterloo?",
      background: "calle-manchester",
      correct: { id: "industrial-q22-correct", text: "Una reforma del Parlamento para que los trabajadores pudieran votar y estar representados", help: "Exacto! Ciudades enormes como Manchester ni siquiera tenían representantes en el Parlamento" },
      distractors: [
        { id: "industrial-q22-d1", text: "Que volviera la monarquía absoluta", help: "No, querían más participación política, no menos" },
        { id: "industrial-q22-d2", text: "Que Inglaterra declarara la guerra a Francia", help: "No, no era un reclamo de política exterior" },
        { id: "industrial-q22-d3", text: "Que se cerraran todas las fábricas", help: "No, querían mejores condiciones y representación, no cerrar las fábricas" },
        { id: "industrial-q22-d4", text: "La independencia de Irlanda", help: "No, era otro tema distinto" },
      ],
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "Liverpool, 1830",
      background: "estacion-tren",
    },
    {
      type: "dialogue",
      character: "stephenson",
      speaker: "George Stephenson",
      text: "Soy George Stephenson. Esta es mi locomotora, la Rocket. Hoy inauguramos la primera línea de ferrocarril entre dos grandes ciudades",
      background: "estacion-tren",
    },
    {
      type: "question",
      character: "stephenson",
      speaker: "George Stephenson",
      text: "¿Qué ciudades unió el ferrocarril inaugurado en 1830?",
      background: "estacion-tren",
      correct: { id: "industrial-q25-correct", text: "Liverpool y Manchester, el puerto y la gran ciudad textil", help: "Exacto! Llevaba pasajeros y también algodón y manufacturas de manera rápida y barata" },
      distractors: [
        { id: "industrial-q25-d1", text: "Londres y París", help: "No, hace falta cruzar el mar para eso. El Eurotúnel llegó casi dos siglos después" },
        { id: "industrial-q25-d2", text: "Manchester y Edimburgo", help: "No, esa línea no fue la primera" },
        { id: "industrial-q25-d3", text: "Liverpool y Nueva York", help: "No no, no se puede ir en tren a través del océano" },
        { id: "industrial-q25-d4", text: "Londres y Dover", help: "No, la primera línea entre ciudades fue otra" },
      ],
    },
    {
      type: "dialogue",
      character: "stephenson",
      speaker: "George Stephenson",
      text: "Con el tren las mercancías llegan rápido y las distancias se acortan. En pocos años todo el país va a estar lleno de rieles",
      background: "estacion-tren",
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "Manchester, 1832",
      background: "calle-manchester",
    },
    {
      type: "dialogue",
      character: "obrero",
      speaker: "Obrero textil",
      text: "En 1831 Manchester ya tenía más de 140.000 habitantes, y sigue creciendo a toda velocidad. Mire cómo vivimos: casas pegadas unas a otras, humo de las chimeneas y agua sucia",
      background: "calle-manchester",
    },
    {
      type: "question",
      character: "obrero",
      speaker: "Obrero textil",
      text: "¿Cómo eran las ciudades industriales?",
      background: "calle-manchester",
      correct: { id: "industrial-q29-correct", text: "Crecían muy rápido, con barrios obreros hacinados, humo y poca higiene, y había epidemias como el cólera", help: "Así es. Esas condiciones generaron mucha enfermedad y muchas muertes" },
      distractors: [
        { id: "industrial-q29-d1", text: "Eran ciudades planificadas, limpias y con agua potable para todos", help: "No no, crecieron sin planificación y las condiciones eran muy malas" },
        { id: "industrial-q29-d2", text: "Eran muy pequeñas y casi sin habitantes", help: "No, crecían a toda velocidad" },
        { id: "industrial-q29-d3", text: "Eran pueblos de campesinos con pocas casas", help: "No, eran grandes ciudades llenas de fábricas" },
        { id: "industrial-q29-d4", text: "Las fábricas se instalaban lejos y nadie vivía cerca", help: "No, los obreros vivían pegados a las fábricas" },
      ],
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "Inglaterra, 1833",
      background: "calle-manchester",
    },
    {
      type: "dialogue",
      character: "obrero",
      speaker: "Obrero textil",
      text: "Por fin el Parlamento tomó cartas en el asunto. Después de muchas denuncias por el trabajo de los niños, se aprobó una ley sobre las fábricas",
      background: "calle-manchester",
    },
    {
      type: "question",
      character: "obrero",
      speaker: "Obrero textil",
      text: "¿Qué estableció la ley fabril de 1833?",
      background: "calle-manchester",
      correct: { id: "industrial-q32-correct", text: "Prohibió el trabajo de los niños menores de 9 años en las fábricas textiles, limitó las horas de los jóvenes y creó inspectores", help: "Exacto! Fue un primer paso, aunque muy limitado. Los inspectores casi no alcanzaban" },
      distractors: [
        { id: "industrial-q32-d1", text: "Prohibió totalmente el trabajo infantil", help: "No, todavía los niños mayores seguían trabajando" },
        { id: "industrial-q32-d2", text: "Estableció la jornada de 8 horas para todos", help: "No, eso se consiguió décadas más tarde, tras muchas luchas" },
        { id: "industrial-q32-d3", text: "Dio vacaciones pagas a los obreros", help: "No, eso llegó mucho después" },
        { id: "industrial-q32-d4", text: "Prohibió las fábricas", help: "Nooo, la industria siguió creciendo" },
      ],
    },
    {
      type: "dialogue",
      character: "owen",
      speaker: "Robert Owen",
      text: "Soy Robert Owen, dueño de una fábrica en New Lanark. Demostré que se puede producir con jornadas más cortas, escuelas para los niños y viviendas dignas. Me dicen soñador, pero me va bien",
      background: "fabrica-textil",
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "Inglaterra, 1838",
      background: "calle-manchester",
    },
    {
      type: "dialogue",
      character: "obrero",
      speaker: "Obrero textil",
      text: "Los obreros se organizan en sindicatos y presentan una Carta del Pueblo. Los llaman cartistas y juntaron millones de firmas",
      background: "calle-manchester",
    },
    {
      type: "question",
      character: "obrero",
      speaker: "Obrero textil",
      text: "¿Qué pedía el movimiento cartista?",
      background: "calle-manchester",
      correct: { id: "industrial-q36-correct", text: "Derecho de voto para todos los hombres, voto secreto y que los trabajadores pudieran ser elegidos", help: "Exacto! Casi todos sus puntos se convirtieron en ley en las décadas siguientes" },
      distractors: [
        { id: "industrial-q36-d1", text: "Abolir el Parlamento", help: "No no, querían que el Parlamento los representara" },
        { id: "industrial-q36-d2", text: "Prohibir los sindicatos", help: "Nooo, era un movimiento de trabajadores" },
        { id: "industrial-q36-d3", text: "Volver al trabajo artesanal en casa", help: "No, ese no era el reclamo principal" },
        { id: "industrial-q36-d4", text: "Aumentar los impuestos a los obreros", help: "No, ni locos" },
      ],
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "Manchester, 1844",
      background: "calle-manchester",
    },
    {
      type: "dialogue",
      character: "engels",
      speaker: "Friedrich Engels",
      text: "Soy Friedrich Engels, un joven alemán. Mi familia tiene una fábrica en Manchester y estoy escribiendo un libro sobre la situación de la clase obrera en Inglaterra",
      background: "calle-manchester",
    },
    {
      type: "question",
      character: "engels",
      speaker: "Friedrich Engels",
      text: "¿Qué dos clases sociales se enfrentaban en la sociedad industrial, según Engels?",
      background: "calle-manchester",
      correct: { id: "industrial-q39-correct", text: "La burguesía, dueña de las fábricas, y el proletariado, que vivía de su trabajo", help: "Exacto! Esas ideas tuvieron muchísima influencia más adelante, por ejemplo en el pensamiento de Karl Marx" },
      distractors: [
        { id: "industrial-q39-d1", text: "Los nobles y los campesinos", help: "No, esa era la sociedad del Antiguo Régimen, antes de la industrialización" },
        { id: "industrial-q39-d2", text: "Los esclavos y los libertos", help: "No, esa división no describe a la sociedad industrial inglesa" },
        { id: "industrial-q39-d3", text: "El clero y el ejército", help: "No no, esas eran otras instituciones" },
        { id: "industrial-q39-d4", text: "Los reyes y las reinas", help: "Nooo, no se trata de eso" },
      ],
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "El Río de la Plata, mediados del siglo XIX",
      background: "estacion-tren",
    },
    {
      type: "dialogue",
      character: "obrero",
      speaker: "Obrero textil",
      text: "La industria inglesa necesitaba materias primas y mercados en todo el mundo. También en el Río de la Plata, donde ya se compraba mucho de lo que se fabricaba en Manchester",
      background: "estacion-tren",
    },
    {
      type: "question",
      character: "obrero",
      speaker: "Obrero textil",
      text: "¿Qué compraba la industria británica al Río de la Plata?",
      background: "estacion-tren",
      correct: { id: "industrial-q42-correct", text: "Cueros, sebo y lana, y más tarde carne y cereales", help: "Exacto! A cambio, el Río de la Plata compraba telas y otros productos industriales. En 1857 se inauguró el primer ferrocarril argentino, con tecnología inglesa" },
      distractors: [
        { id: "industrial-q42-d1", text: "Máquinas de vapor y locomotoras", help: "No, esas las fabricaba Inglaterra y las compraba el Río de la Plata" },
        { id: "industrial-q42-d2", text: "Acero y petróleo", help: "No, no eran los productos del Río de la Plata en esa época" },
        { id: "industrial-q42-d3", text: "Algodón y té", help: "No, eso venía de otras regiones, como Estados Unidos o la India" },
        { id: "industrial-q42-d4", text: "Tabaco y café", help: "No, eran productos de otras regiones" },
      ],
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "Londres, 1851",
      background: "estacion-tren",
    },
    {
      type: "dialogue",
      character: "obrero",
      speaker: "Obrero textil",
      text: "Gran Exposición universal en el Palacio de Cristal: Inglaterra se muestra al mundo como el taller del planeta, con máquinas, telas y locomotoras de todo tipo",
      background: "estacion-tren",
    },
    {
      type: "dialogue",
      character: "obrero",
      speaker: "Obrero textil",
      text: "Gracias por acompañarme en este viaje. La industria cambió la forma de producir, de vivir y de pensar. Tome este engranaje como recuerdo ¡Hasta la próxima!",
      background: "estacion-tren",
    },
  ],
};
