import type { Chapter } from "../types";

export const intro: Chapter = {
  id: "intro",
  title: "Tutorial",
  accentColor: "rgba(40, 167, 69, 0.6)",
  reward: {
    name: "Libro de historia",
    image: "book",
    text: "Completaste el tutorial. Selecciona cualquier otra época para empezar a jugar",
  },
  screens: [
    {
      type: "dialogue",
      character: "profe",
      speaker: "Profe historia",
      text: "Bienvenides a nuestra biblioteca escolar! Se van a dar cuenta rápido que esta no es una biblioteca común y corriente.",
      background: "biblioteca",
    },
    {
      type: "dialogue",
      character: "profe",
      speaker: "Profe historia",
      text: "Esta es una biblioteca mágica! Acá vamos a aprender historia de una forma particular",
      background: "biblioteca",
    },
    {
      type: "dialogue",
      character: "profe",
      speaker: "Profe historia",
      text: "Acá vamos a ¡VIAJAR EN EL TIEMPO!",
      background: "biblioteca",
    },
    {
      type: "dialogue",
      character: "profe",
      speaker: "Profe historia",
      text: "¿Me están prestando atención?",
      background: "biblioteca",
    },
    {
      type: "question",
      character: "profe",
      speaker: "Profe historia",
      text: "¿Me están escuchando?",
      background: "biblioteca",
      correct: { id: "intro-q5-correct", text: "Sí, vamos a viajar en el tiempo", help: "Muy bien! Están atentes" },
      distractors: [
        { id: "intro-q5-d1", text: "Sí, podemos traer personajes del pasado", help: "Nooo! Nosotres vamos a viajar en el tiempo, nadie va a venir" },
        { id: "intro-q5-d2", text: "Sí, vamos a hacer experimentos de química", help: "¡Estamos en historia! No, vamos a poder visitar épocas de la historia" },
        { id: "intro-q5-d3", text: "Eeehh… no, estaba con el celu", help: "Dejenló un segundo! Repito, vamos a viajar en el tiempo a conocer la historia" },
        { id: "intro-q5-d4", text: "¿Podría repetir por favor?", help: "¡Cómo no! Vamos a viajar en el tiempo para conocer las diferentes épocas históricas" },
      ],
    },
    {
      type: "dialogue",
      character: "profe",
      speaker: "Profe historia",
      text: "Así me gusta, prestando atención.",
      background: "biblioteca",
    },
    {
      type: "dialogue",
      character: "profe",
      speaker: "Profe historia",
      text: "Ustedes se preguntarán ¿Cómo vamos a viajar? Vamos a usar esto:",
      background: "biblioteca",
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "...",
      background: "libro-magico",
    },
    {
      type: "dialogue",
      character: "profe",
      speaker: "Profe historia",
      text: "Este es nuestro PASEA HISTORIAS, es un libro mágico que nos permite viajar a cualquier época histórica y convertirnos en personajes de la época.",
      background: "libro-magico",
    },
    {
      type: "dialogue",
      character: "profe",
      speaker: "Profe historia",
      text: "En nuestras visitas tenemos que pasar desapercibides y contestar bien a todas las preguntas que nos hagan las personas de cada época",
      background: "libro-magico",
    },
    {
      type: "dialogue",
      character: "profe",
      speaker: "Profe historia",
      text: "¡Pero no se asusten! Que yo voy a estar con ustedes ayudándoles si no saben algo.",
      background: "libro-magico",
    },
    {
      type: "question",
      character: "profe",
      speaker: "Profe historia",
      text: "¿Hasta acá estamos?",
      background: "biblioteca",
      correct: { id: "intro-q12-correct", text: "Sí, en cada época nos van a hacer preguntas y si no sabemos algo, nos vas a ayudar", help: "Exacto, así que tranquiles que no pasa nada si no saben algo. ¡El objetivo es aprender!" },
      distractors: [
        { id: "intro-q12-d1", text: "Sí, vos nos vas a hacer preguntas y tenemos que contestar bien", help: "¿Viste que estaban distraides? Las preguntas se las hacen los personajes de las épocas, yo sólo les ayudo si no saben algo" },
        { id: "intro-q12-d2", text: "Sí, le tenemos que hacer preguntas a los personajes para aprender", help: "Nooo, ustedes tienen que contestar sus preguntas, no hacerlas" },
        { id: "intro-q12-d3", text: "Sí, hay que escribir en el pasea historias lo que nos van contando", help: "No no, el pasea historias sirve para viajar en el tiempo, después los personajes nos van a hacer preguntas" },
        { id: "intro-q12-d4", text: "Estaba con el celu ¿Qué dijo?", help: "¡Más atentes por favor! Los personajes en cada época nos van a hacer preguntas y hay que contestarlas bien, si no saben alguna, yo los ayudo" },
      ],
    },
    {
      type: "dialogue",
      character: "profe",
      speaker: "Profe historia",
      text: "Exacto, bien, ya sabemos que vamos a hacer entonces.",
      background: "biblioteca",
    },
    {
      type: "dialogue",
      character: "profe",
      speaker: "Profe historia",
      text: "Entonces ¿Qué quieren visitar? ¿La revolución francesa? ¿La independencia Argentina? ¿La llegada de Colón? Todo es posible con este libro.",
      background: "biblioteca",
    },
    {
      type: "dialogue",
      character: "profe",
      speaker: "Profe historia",
      text: "Peeeeero, acuerdense que seguimos en la escuela, así que tienen tarea.",
      background: "biblioteca",
    },
    {
      type: "dialogue",
      character: "profe",
      speaker: "Profe historia",
      text: "Todes los que viajen tienen que traer un recuerdo de la época que visiten, algo característico del momento, piensenlo como un souvenir. Nada más que ese souvenir queda acá, en la escuela, como parte de nuestra colección.",
      background: "biblioteca",
    },
    {
      type: "dialogue",
      character: "profe",
      speaker: "Profe historia",
      text: "Bueno, basta de charla que se nos va a la hora ¿Quién empieza?",
      background: "biblioteca",
    },
  ],
};
