import type { Chapter } from "../types";

export const pueblo: Chapter = {
  id: "pueblo",
  title: "Revolución de Mayo",
  accentColor: "rgba(46, 158, 147, 0.6)",
  reward: {
    name: "Escarapela de 1810",
    image: "escarapela",
    text: "Completaste la revolución de mayo de 1810 como parte del pueblo. Completa la historia desde la mirada realista para conseguir la escarapela completa",
  },
  screens: [
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "...",
      background: "viernes-18",
    },
    {
      type: "dialogue",
      character: "vecino",
      speaker: "Vecino del barrio",
      text: "Buen día, vecino ¡Pase, pase! Acá en la pulpería no se habla de otra cosa desde el lunes: llegó un barco inglés con diarios de Europa y las noticias son muy malas.",
      background: "pulperia",
    },
    {
      type: "dialogue",
      character: "vecino",
      speaker: "Vecino del barrio",
      text: "Dicen que los soldados de Napoleón ocuparon casi toda España ¿Usted sabe lo que eso significa?",
      background: "pulperia",
    },
    {
      type: "question",
      character: "vecino",
      speaker: "Vecino del barrio",
      text: "¿Qué dicen los diarios que llegaron en el barco inglés?",
      background: "pulperia",
      correct: { id: "pueblo-q4-correct", text: "Que los franceses dominan casi toda España y la Junta que gobernaba en nombre del rey ya no existe", help: "Exacto! Sin esa Junta, mucha gente se pregunta con qué derecho sigue mandando el virrey Cisneros, que había sido designado por ella" },
      distractors: [
        { id: "pueblo-q4-d1", text: "Que el rey Fernando VII volvió a Madrid y gobierna otra vez", help: "No no, Fernando VII está preso en Francia y recién va a volver a España en 1814" },
        { id: "pueblo-q4-d2", text: "Que los ingleses volvieron a atacar Buenos Aires", help: "No, a los ingleses los rechazamos en 1806 y 1807, y ahora son aliados de España contra Napoleón" },
        { id: "pueblo-q4-d3", text: "Que España le concedió la independencia a América", help: "Nooo, España no pensaba dar la independencia. Eso lo van a lograr los propios americanos más adelante" },
        { id: "pueblo-q4-d4", text: "Que Napoleón murió en una batalla", help: "No, Napoleón está en su mejor momento y domina buena parte de Europa. Recién va a morir en 1821" },
      ],
    },
    {
      type: "dialogue",
      character: "vecino",
      speaker: "Vecino del barrio",
      text: "Hoy mismo el virrey hizo publicar una proclama pidiendo tranquilidad, pero la noticia ya anda de boca en boca por toda la ciudad",
      background: "pulperia",
    },
    {
      type: "dialogue",
      character: "vecino",
      speaker: "Vecino del barrio",
      text: "Hace dos años que los españoles no tienen rey ¿Se acuerda a quién tenía preso Napoleón?",
      background: "pulperia",
    },
    {
      type: "question",
      character: "vecino",
      speaker: "Vecino del barrio",
      text: "¿Qué rey de España estaba prisionero de Napoleón?",
      background: "pulperia",
      correct: { id: "pueblo-q7-correct", text: "Fernando VII", help: "Sí! Los españoles lo llamaban \"el Deseado\" y en su nombre se formaron juntas de gobierno por toda España" },
      distractors: [
        { id: "pueblo-q7-d1", text: "Carlos IV", help: "Casi! Carlos IV, su padre, también tuvo que abdicar y vivía en el exilio, pero el rey que todos esperaban era su hijo Fernando VII" },
        { id: "pueblo-q7-d2", text: "José Bonaparte", help: "No no, ese era el hermano de Napoleón, a quien puso como rey de España. Los españoles lo rechazaban" },
        { id: "pueblo-q7-d3", text: "Luis XVI", help: "No, ese era rey de Francia y murió en la guillotina en 1793" },
        { id: "pueblo-q7-d4", text: "Carlos III", help: "No, ese rey murió en 1788, mucho antes de todo esto" },
      ],
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "...",
      background: "sabado-19",
    },
    {
      type: "dialogue",
      character: "vecino",
      speaker: "Vecino del barrio",
      text: "Mire cuánta gente. Desde temprano hay corrillos en la plaza y en las pulperías, todos quieren saber qué va a pasar con el virrey",
      background: "plaza-victoria",
    },
    {
      type: "dialogue",
      character: "french",
      speaker: "Domingo French",
      text: "Buen día, soy Domingo French. Junto con mi amigo Antonio Beruti andamos juntando gente decidida: jóvenes, artesanos, milicianos. Los realistas nos llaman \"chisperos\" o \"infernales\"",
      background: "plaza-victoria",
    },
    {
      type: "dialogue",
      character: "french",
      speaker: "Domingo French",
      text: "Muchos de los que estamos acá peleamos contra los ingleses en 1806 y 1807. Sabemos lo que vale este pueblo cuando se organiza",
      background: "plaza-victoria",
    },
    {
      type: "question",
      character: "french",
      speaker: "Domingo French",
      text: "¿Por qué la gente de Buenos Aires se sentía con fuerza para reclamar?",
      background: "plaza-victoria",
      correct: { id: "pueblo-q12-correct", text: "Porque en 1806 y 1807 los vecinos se organizaron en milicias y rechazaron a los ingleses casi sin ayuda de España", help: "Exacto! Después de las invasiones inglesas el pueblo estaba armado y organizado en regimientos como los Patricios, y se había dado cuenta de su propia fuerza" },
      distractors: [
        { id: "pueblo-q12-d1", text: "Porque España les había regalado mucho armamento para pelear contra Napoleón", help: "No, en esos años España no mandaba ni armas ni tropas, estaba ocupada con sus propios problemas" },
        { id: "pueblo-q12-d2", text: "Porque Inglaterra les prometió ayuda militar", help: "No no, los ingleses fueron justamente los que invadieron en 1806 y 1807, y fueron rechazados" },
        { id: "pueblo-q12-d3", text: "Porque Napoleón había mandado un ejército a Buenos Aires", help: "No, Napoleón nunca mandó tropas al Río de la Plata" },
        { id: "pueblo-q12-d4", text: "Porque ya habían declarado la independencia", help: "Falta mucho! La independencia se declara recién en 1816" },
      ],
    },
    {
      type: "dialogue",
      character: "beruti",
      speaker: "Antonio Beruti",
      text: "Yo soy Antonio Beruti. Nuestros amigos Castelli y Belgrano, que son hombres de leyes y de letras, quieren pedir un cabildo abierto",
      background: "plaza-victoria",
    },
    {
      type: "dialogue",
      character: "beruti",
      speaker: "Antonio Beruti",
      text: "Nosotros nos ocupamos de que en la calle se escuche lo que piensa el pueblo",
      background: "plaza-victoria",
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "...",
      background: "domingo-20",
    },
    {
      type: "dialogue",
      character: "vecino",
      speaker: "Vecino del barrio",
      text: "Parece que el alcalde Lezica y Saavedra, el jefe de los Patricios, hablaron con Cisneros. Como los jefes militares no le aseguraron su apoyo, el virrey terminó aceptando que haya un cabildo abierto",
      background: "plaza-victoria",
    },
    {
      type: "dialogue",
      character: "vecino",
      speaker: "Vecino del barrio",
      text: "Pero ojo, no es una asamblea para cualquiera. Se invita a los \"vecinos\" ¿Sabe quiénes eran considerados vecinos?",
      background: "plaza-victoria",
    },
    {
      type: "question",
      character: "vecino",
      speaker: "Vecino del barrio",
      text: "¿Quiénes eran considerados \"vecinos\" en 1810?",
      background: "plaza-victoria",
      correct: { id: "pueblo-q18-correct", text: "Los hombres respetables con propiedades, comercio, cargos o profesiones. Quedaban afuera los peones, los esclavos y las mujeres", help: "Así es. La palabra \"pueblo\" solía referirse a esa élite, por eso mucha gente quedaba afuera y tenía que hacerse oír en la plaza" },
      distractors: [
        { id: "pueblo-q18-d1", text: "Todos los habitantes de la ciudad, incluso los esclavos", help: "No no, la gran mayoría de la población quedaba afuera de las decisiones" },
        { id: "pueblo-q18-d2", text: "Solamente los militares", help: "No, también eran vecinos comerciantes, abogados, sacerdotes y propietarios. Pero la gente humilde quedaba afuera" },
        { id: "pueblo-q18-d3", text: "Solamente los españoles nacidos en España", help: "No, también criollos de buena posición. Aunque es cierto que muchos cargos importantes eran para españoles" },
        { id: "pueblo-q18-d4", text: "Todos los mayores de 18 años", help: "No existía el voto universal, para eso faltaban más de cien años" },
      ],
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "...",
      background: "lunes-21",
    },
    {
      type: "dialogue",
      character: "vecino",
      speaker: "Vecino del barrio",
      text: "Qué movimiento! Hoy el Cabildo repartió las invitaciones para el cabildo abierto de mañana, pero en la plaza hay mucha más gente que no fue invitada",
      background: "plaza-victoria",
    },
    {
      type: "question",
      character: "vecino",
      speaker: "Vecino del barrio",
      text: "¿A cuántas personas se invitó al cabildo abierto?",
      background: "plaza-victoria",
      correct: { id: "pueblo-q21-correct", text: "A unos 450 vecinos, en una ciudad de decenas de miles de habitantes", help: "Exacto! Fueron muy pocos. Y encima, no todos los invitados iban a asistir" },
      distractors: [
        { id: "pueblo-q21-d1", text: "A todos los habitantes, casi 40.000 personas", help: "No no, eso hubiera sido imposible. Se invitó a un grupo muy reducido" },
        { id: "pueblo-q21-d2", text: "Solamente a 20 personas", help: "No, fueron bastantes más. Pero igual muy pocas para toda la ciudad" },
        { id: "pueblo-q21-d3", text: "A unas 5.000 personas", help: "No, fueron muchas menos" },
        { id: "pueblo-q21-d4", text: "A 100 militares", help: "No, se invitó a vecinos de distintos oficios y profesiones, no solo a militares" },
      ],
    },
    {
      type: "dialogue",
      character: "french",
      speaker: "Domingo French",
      text: "El Cabildo quiere controlar quién entra. Por eso hay tanta gente reunida: queremos que sepan que el pueblo está atento",
      background: "cabildo-lleno",
    },
    {
      type: "question",
      character: "beruti",
      speaker: "Antonio Beruti",
      text: "¿Qué papel cumplían French y Beruti?",
      background: "cabildo-lleno",
      correct: { id: "pueblo-q23-correct", text: "Movilizaban a la gente de la plaza para presionar por el cambio de gobierno", help: "Así es! Sus detractores los llamaban la \"Legión Infernal\" pero ellos se veían como defensores de la causa del pueblo" },
      distractors: [
        { id: "pueblo-q23-d1", text: "Eran oficiales españoles enviados a reprimir a la multitud", help: "No no, eran criollos comprometidos con la causa revolucionaria" },
        { id: "pueblo-q23-d2", text: "Eran recaudadores de impuestos", help: "No, no tenían nada que ver con los impuestos" },
        { id: "pueblo-q23-d3", text: "Eran espías ingleses", help: "No, los ingleses no tenían nada que ver con esta historia en 1810" },
        { id: "pueblo-q23-d4", text: "Eran miembros del Cabildo y defendían al virrey", help: "No, ellos estaban afuera del Cabildo, en la plaza, y querían que Cisneros dejara el mando" },
      ],
    },
    {
      type: "dialogue",
      character: "saavedra",
      speaker: "Cornelio Saavedra",
      text: "Calma, muchachos, calma. No hace falta violencia: mañana habrá cabildo abierto y las tropas mantendrán el orden",
      background: "cabildo-lleno",
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "...",
      background: "martes-22",
    },
    {
      type: "dialogue",
      character: "vecino",
      speaker: "Vecino del barrio",
      text: "Hoy se abre el cabildo abierto. Hace frío y garúa, pero la plaza está llena. De los 450 invitados solo llegaron 251",
      background: "plaza-victoria",
    },
    {
      type: "dialogue",
      character: "vecino",
      speaker: "Vecino del barrio",
      text: "Nosotros no podemos entrar, pero los que salen cuentan lo que se discute adentro ¿Sabe cuál es el tema?",
      background: "plaza-victoria",
    },
    {
      type: "question",
      character: "vecino",
      speaker: "Vecino del barrio",
      text: "¿Qué se discute en el cabildo abierto?",
      background: "plaza-victoria",
      correct: { id: "pueblo-q28-correct", text: "Si el virrey Cisneros debe seguir gobernando después de la caída de la Junta en España", help: "Exacto! El gran tema es quién debe gobernar mientras el rey esté preso" },
      distractors: [
        { id: "pueblo-q28-d1", text: "Si Buenos Aires debe declarar la independencia de España", help: "No no, nadie habla de independencia todavía. Eso llegaría en 1816" },
        { id: "pueblo-q28-d2", text: "Si se firma la paz con Napoleón", help: "No, eso lo decidían en Europa, no en Buenos Aires" },
        { id: "pueblo-q28-d3", text: "Si se construye un nuevo puerto", help: "No, hay un tema político mucho más urgente" },
        { id: "pueblo-q28-d4", text: "Si se expulsa a los ingleses de la ciudad", help: "No, los ingleses ya fueron derrotados en 1807" },
      ],
    },
    {
      type: "dialogue",
      character: "vecino",
      speaker: "Vecino del barrio",
      text: "Dicen que Castelli sostuvo que, caído el gobierno de España, el poder vuelve al pueblo. Y que Paso lo apoyó",
      background: "plaza-victoria",
    },
    {
      type: "question",
      character: "vecino",
      speaker: "Vecino del barrio",
      text: "¿Qué quiere decir que \"el poder vuelve al pueblo\"?",
      background: "plaza-victoria",
      correct: { id: "pueblo-q30-correct", text: "Que sin rey ni gobierno legítimo en España, los pueblos recuperan el derecho de formar su propio gobierno, en nombre del rey", help: "Exacto! A eso se le llamaba \"retroversión de la soberanía\", la gran idea política de estos días" },
      distractors: [
        { id: "pueblo-q30-d1", text: "Que el pueblo paga menos impuestos", help: "No no, no tiene nada que ver con los impuestos" },
        { id: "pueblo-q30-d2", text: "Que los pueblos de América pasan a depender de Inglaterra", help: "No, justamente se trata de que decidan los de acá" },
        { id: "pueblo-q30-d3", text: "Que el virrey se convierte en rey", help: "No, nadie quiere un rey nuevo, se sigue hablando del rey Fernando VII" },
        { id: "pueblo-q30-d4", text: "Que se prohíbe a los españoles vivir en América", help: "No no, nadie plantea eso" },
      ],
    },
    {
      type: "dialogue",
      character: "vecino",
      speaker: "Vecino del barrio",
      text: "La votación es pública y a viva voz: cada vecino dice su voto y queda anotado. Mañana el Cabildo hará el recuento",
      background: "plaza-victoria",
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "...",
      background: "miercoles-23",
    },
    {
      type: "dialogue",
      character: "vecino",
      speaker: "Vecino del barrio",
      text: "Pasamos todo el día esperando los resultados ¿Qué cree que votó la mayoría?",
      background: "plaza-victoria",
    },
    {
      type: "question",
      character: "vecino",
      speaker: "Vecino del barrio",
      text: "¿Qué decidió la mayoría del cabildo abierto?",
      background: "plaza-victoria",
      correct: { id: "pueblo-q34-correct", text: "Que Cisneros dejara el mando y que el Cabildo gobernara hasta formar una Junta", help: "Exacto! Una amplia mayoría votó contra la continuidad del virrey" },
      distractors: [
        { id: "pueblo-q34-d1", text: "Que Cisneros siguiera como único gobernante", help: "No, la mayoría votó a favor de que dejara el mando" },
        { id: "pueblo-q34-d2", text: "Que gobernara el obispo Lué", help: "No, el obispo defendió justamente que siguiera el virrey" },
        { id: "pueblo-q34-d3", text: "Que Buenos Aires se declarara independiente", help: "No, todavía se gobernaba en nombre del rey Fernando VII" },
        { id: "pueblo-q34-d4", text: "Que gobernara el pueblo sin autoridades", help: "No no, la idea era formar una Junta de gobierno" },
      ],
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "...",
      background: "jueves-24",
    },
    {
      type: "dialogue",
      character: "vecino",
      speaker: "Vecino del barrio",
      text: "Ya salió el anuncio del Cabildo. Pero hay algo raro, la gente está muy enojada ¿Sabe qué hicieron con el resultado de la votación?",
      background: "cabildo-lleno",
    },
    {
      type: "question",
      character: "vecino",
      speaker: "Vecino del barrio",
      text: "¿Qué hizo el Cabildo con el resultado de la votación?",
      background: "cabildo-lleno",
      correct: { id: "pueblo-q37-correct", text: "Formó una Junta que tenía a Cisneros como presidente", help: "Sí! Cambiaron el nombre pero el virrey seguía mandando. Por eso el pueblo se sintió traicionado" },
      distractors: [
        { id: "pueblo-q37-d1", text: "Declaró la independencia", help: "No, eso recién pasa en 1816" },
        { id: "pueblo-q37-d2", text: "Encarceló a Cisneros", help: "No, al contrario, lo dejó como presidente de la nueva Junta" },
        { id: "pueblo-q37-d3", text: "Nombró presidente a Mariano Moreno", help: "No, Moreno todavía no tenía ningún cargo" },
        { id: "pueblo-q37-d4", text: "Disolvió el cabildo abierto sin decidir nada", help: "No, sí se decidió algo, y fue lo que enojó al pueblo" },
      ],
    },
    {
      type: "dialogue",
      character: "french",
      speaker: "Domingo French",
      text: "Nos engañaron! Eso no es lo que votó la mayoría ni lo que quiere el pueblo. Vamos a hablar con Saavedra y los jefes militares",
      background: "cabildo-lleno",
    },
    {
      type: "dialogue",
      character: "saavedra",
      speaker: "Cornelio Saavedra",
      text: "Tranquilos, muchachos. Esta noche Castelli y yo vamos a renunciar a esa Junta, que tiene como presidente al virrey",
      background: "cabildo-lleno",
    },
    {
      type: "question",
      character: "saavedra",
      speaker: "Cornelio Saavedra",
      text: "¿Por qué no pudo sostenerse la Junta presidida por Cisneros?",
      background: "cabildo-lleno",
      correct: { id: "pueblo-q40-correct", text: "Porque Saavedra y Castelli renunciaron y ni el pueblo ni los jefes militares la aceptaron", help: "Exacto! Sin apoyo de la gente ni de las tropas, el virrey se quedaba sin sostén" },
      distractors: [
        { id: "pueblo-q40-d1", text: "Porque Cisneros se fue a España esa misma noche", help: "No no, Cisneros todavía estaba en Buenos Aires" },
        { id: "pueblo-q40-d2", text: "Porque llegó un ejército desde Lima", help: "No, nadie llegó desde Lima" },
        { id: "pueblo-q40-d3", text: "Porque los ingleses lo exigieron", help: "No, los ingleses no tenían nada que ver" },
        { id: "pueblo-q40-d4", text: "Porque se acabó el dinero para pagar a los funcionarios", help: "No, el problema era político, no de dinero" },
      ],
    },
    {
      type: "dialogue",
      character: "beruti",
      speaker: "Antonio Beruti",
      text: "Mañana nos juntamos todos en la plaza. Que los del Cabildo se enteren de lo que quiere el pueblo",
      background: "cabildo-lleno",
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "...",
      background: "viernes-25",
    },
    {
      type: "dialogue",
      character: "vecino",
      speaker: "Vecino del barrio",
      text: "Qué garúa, vecino! Pero fíjese cuánta gente hay en la plaza, delante del Cabildo",
      background: "plaza-victoria",
    },
    {
      type: "dialogue",
      character: "vecino",
      speaker: "Vecino del barrio",
      text: "Mire, French y Beruti andan repartiendo cintas distintivas entre la gente",
      background: "plaza-victoria",
    },
    {
      type: "question",
      character: "vecino",
      speaker: "Vecino del barrio",
      text: "¿Qué repartían French y Beruti entre la gente, según la tradición?",
      background: "plaza-victoria",
      correct: { id: "pueblo-q45-correct", text: "Cintas distintivas para reconocer a los partidarios del cambio, que según la tradición eran celestes y blancas", help: "Exacto! Los historiadores discuten de qué colores eran (Mitre se basó en la tradición oral), pero sí usaron distintivos. La escarapela nacional se creó oficialmente recién en 1812" },
      distractors: [
        { id: "pueblo-q45-d1", text: "Banderas rojas y amarillas, los colores de España", help: "No, justamente querían diferenciarse de los símbolos de la Corona" },
        { id: "pueblo-q45-d2", text: "Cintas negras en señal de luto", help: "No, no eran de luto, eran de esperanza" },
        { id: "pueblo-q45-d3", text: "Panfletos a favor del virrey", help: "No no, estaban en contra del virrey" },
        { id: "pueblo-q45-d4", text: "Sombreros ingleses", help: "No, eso no tiene nada que ver" },
      ],
    },
    {
      type: "dialogue",
      character: "french",
      speaker: "Domingo French",
      text: "Pueblo de Buenos Aires! Hoy nos reunimos para pedir que Cisneros deje el mando y que se forme una Junta con hombres de confianza del pueblo",
      background: "plaza-victoria",
    },
    {
      type: "dialogue",
      character: "vecino",
      speaker: "Vecino del barrio",
      text: "Cuentan que alguien gritó \"El pueblo quiere saber de qué se trata\" y que se presentó un petitorio con cientos de firmas",
      background: "plaza-victoria",
    },
    {
      type: "question",
      character: "vecino",
      speaker: "Vecino del barrio",
      text: "¿Qué pedía el pueblo frente al Cabildo?",
      background: "plaza-victoria",
      correct: { id: "pueblo-q48-correct", text: "Que Cisneros dejara definitivamente el mando y se formara una nueva Junta de gobierno", help: "Exacto! Y el Cabildo, con tanta presión, terminó aceptando" },
      distractors: [
        { id: "pueblo-q48-d1", text: "Que le subieran el sueldo a los soldados", help: "No, el reclamo era político, no de sueldos" },
        { id: "pueblo-q48-d2", text: "Que Cisneros siguiera en el mando", help: "No no, justamente querían que se fuera" },
        { id: "pueblo-q48-d3", text: "La independencia total de España", help: "No, todavía se pedía una Junta que gobernara en nombre del rey" },
        { id: "pueblo-q48-d4", text: "Que se retiraran los Patricios de la plaza", help: "No, los Patricios apoyaban al pueblo" },
      ],
    },
    {
      type: "dialogue",
      character: "vecino",
      speaker: "Vecino del barrio",
      text: "Ya está! Desde el balcón del Cabildo leyeron la lista: Saavedra será el presidente, Paso y Moreno los secretarios, y Castelli, Belgrano, Azcuénaga, Alberti, Matheu y Larrea los vocales",
      background: "plaza-victoria",
    },
    {
      type: "question",
      character: "vecino",
      speaker: "Vecino del barrio",
      text: "¿En nombre de quién iba a gobernar la nueva Junta?",
      background: "plaza-victoria",
      correct: { id: "pueblo-q50-correct", text: "De Fernando VII, el rey preso", help: "Sí! Gobernaban sin romper con el rey legítimo. A eso se le llamó \"la máscara de Fernando\" y le dio tranquilidad a mucha gente" },
      distractors: [
        { id: "pueblo-q50-d1", text: "Del Consejo de Regencia de Cádiz", help: "No, la Junta no reconoció a la Regencia, que había sido nombrada sin consultar a América" },
        { id: "pueblo-q50-d2", text: "De la independencia argentina", help: "No, la independencia llega en 1816 y el país todavía ni se llamaba Argentina" },
        { id: "pueblo-q50-d3", text: "De Napoleón", help: "Nooo, Napoleón era justamente el enemigo" },
        { id: "pueblo-q50-d4", text: "De Inglaterra", help: "No no, los ingleses eran apenas aliados de España" },
      ],
    },
    {
      type: "dialogue",
      character: "vecino",
      speaker: "Vecino del barrio",
      text: "Algunos poderosos nos llamaban \"populacho\". Pero hoy el populacho escribió la historia ¡Viva la revolución!",
      background: "plaza-victoria",
    },
    {
      type: "dialogue",
      character: "french",
      speaker: "Domingo French",
      text: "Gracias por acompañarnos en estos días. Tome esta cinta como recuerdo, la va a necesitar para armar su escarapela",
      background: "plaza-victoria",
    },
    {
      type: "dialogue",
      character: "beruti",
      speaker: "Antonio Beruti",
      text: "Hoy es el principio de un camino largo. Todavía queda mucho por hacer ¡Muchas gracias!",
      background: "plaza-victoria",
    },
  ],
};
