import type { Chapter } from "../types";

export const realista: Chapter = {
  id: "realista",
  title: "Revolución de Mayo",
  accentColor: "rgba(61, 158, 46, 0.6)",
  reward: {
    name: "Escarapela de 1810",
    image: "escarapela",
    text: "Completaste la revolución de mayo de 1810 desde la mirada realista. Ya conoces las tres miradas de la semana que cambió el Río de la Plata",
  },
  screens: [
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "...",
      background: "viernes-18",
    },
    {
      type: "dialogue",
      character: "cisneros",
      speaker: "Baltasar Hidalgo de Cisneros",
      text: "Bienvenido al Fuerte de Buenos Aires. Soy Baltasar Hidalgo de Cisneros, virrey del Río de la Plata y marino de la Real Armada, veterano de la batalla de Trafalgar",
      background: "fuerte",
    },
    {
      type: "dialogue",
      character: "cisneros",
      speaker: "Baltasar Hidalgo de Cisneros",
      text: "Lo designo mi hombre de confianza en estos días difíciles. Su misión será ayudarme a mantener estos dominios fieles a la Corona",
      background: "fuerte",
    },
    {
      type: "dialogue",
      character: "cisneros",
      speaker: "Baltasar Hidalgo de Cisneros",
      text: "Le explico el panorama: en 1808 el emperador Napoleón invadió España, tomó prisionero al rey Fernando VII y puso en el trono a su hermano José ¿Sabe cómo respondió el pueblo español?",
      background: "fuerte",
    },
    {
      type: "question",
      character: "cisneros",
      speaker: "Baltasar Hidalgo de Cisneros",
      text: "¿Cómo respondió el pueblo español a la invasión francesa?",
      background: "fuerte",
      correct: { id: "realista-q5-correct", text: "Formando juntas de gobierno y resistiendo en nombre de Fernando VII", help: "Tal cual! Y Inglaterra se convirtió en aliada de España para pelear contra Napoleón" },
      distractors: [
        { id: "realista-q5-d1", text: "Aceptando enseguida a José Bonaparte como rey", help: "No no, hubo españoles que lo apoyaron, pero la gran mayoría lo rechazó y resistió" },
        { id: "realista-q5-d2", text: "Declarando una república", help: "No, los españoles seguían fieles a su rey Fernando VII" },
        { id: "realista-q5-d3", text: "Pidiendo ayuda militar a Rusia", help: "No, la ayuda vino de Inglaterra" },
        { id: "realista-q5-d4", text: "Rindiéndose y disolviendo el ejército", help: "No! Hubo una larga guerra de resistencia, llamada Guerra de la Independencia española" },
      ],
    },
    {
      type: "dialogue",
      character: "cisneros",
      speaker: "Baltasar Hidalgo de Cisneros",
      text: "Esas juntas se unieron en una Junta Central que gobernó en nombre del rey. Pero este año los franceses avanzaron sobre Andalucía y tomaron Sevilla, y la Junta Central se disolvió",
      background: "fuerte",
    },
    {
      type: "question",
      character: "cisneros",
      speaker: "Baltasar Hidalgo de Cisneros",
      text: "¿Qué reemplazó a la Junta Central en España?",
      background: "fuerte",
      correct: { id: "realista-q7-correct", text: "Un Consejo de Regencia instalado en Cádiz", help: "Exacto! Cádiz era de las pocas ciudades que seguían resistiendo a los franceses" },
      distractors: [
        { id: "realista-q7-d1", text: "Las Cortes de Cádiz", help: "Todavía no! Las Cortes recién se van a reunir en septiembre de este año" },
        { id: "realista-q7-d2", text: "José Bonaparte", help: "No, él era el rey que había impuesto Napoleón, no el reemplazo de la Junta" },
        { id: "realista-q7-d3", text: "Un virrey enviado desde Lima", help: "No no, eso no tiene sentido, Lima es otro virreinato" },
        { id: "realista-q7-d4", text: "El rey Carlos IV, que volvió del exilio", help: "No, Carlos IV seguía fuera de España" },
      ],
    },
    {
      type: "dialogue",
      character: "cisneros",
      speaker: "Baltasar Hidalgo de Cisneros",
      text: "La noticia llegó el lunes en un barco inglés y hoy publiqué una proclama para pedir calma. Pero ya hay quienes dicen que, sin la Junta que me nombró, no tengo derecho a mandar",
      background: "fuerte",
    },
    {
      type: "dialogue",
      character: "cisneros",
      speaker: "Baltasar Hidalgo de Cisneros",
      text: "No es la primera vez que esto pasa en América. Usted debe saber lo que sucedió el año pasado",
      background: "fuerte",
    },
    {
      type: "question",
      character: "cisneros",
      speaker: "Baltasar Hidalgo de Cisneros",
      text: "¿Qué ocurrió en 1809 en ciudades como Chuquisaca y La Paz?",
      background: "fuerte",
      correct: { id: "realista-q10-correct", text: "Hubo levantamientos que formaron juntas propias y fueron reprimidos por tropas realistas", help: "Sí! Fueron las primeras señales de descontento. Se reprimieron con fuerza y el líder paceño Pedro Domingo Murillo fue ejecutado en enero de este año" },
      distractors: [
        { id: "realista-q10-d1", text: "Fueron ocupadas por el ejército de Napoleón", help: "No no, los franceses nunca llegaron a América" },
        { id: "realista-q10-d2", text: "Se declararon repúblicas independientes reconocidas por España", help: "Nooo, la Corona jamás las reconoció y las reprimió" },
        { id: "realista-q10-d3", text: "Fueron destruidas por un terremoto", help: "No, el problema fue político, no natural" },
        { id: "realista-q10-d4", text: "No pasó nada, fue un año tranquilo", help: "No no! Fue un año de mucha tensión en el Alto Perú" },
      ],
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "...",
      background: "sabado-19",
    },
    {
      type: "dialogue",
      character: "cisneros",
      speaker: "Baltasar Hidalgo de Cisneros",
      text: "Los criollos, con Castelli y Belgrano a la cabeza, andan pidiendo un cabildo abierto al alcalde Lezica. El regente de la Real Audiencia, Lucas Muñoz y Cubero, me aconseja mano firme",
      background: "fuerte",
    },
    {
      type: "question",
      character: "cisneros",
      speaker: "Baltasar Hidalgo de Cisneros",
      text: "¿Cuál era la función de la Real Audiencia?",
      background: "fuerte",
      correct: { id: "realista-q13-correct", text: "Era el tribunal superior del rey, que impartía justicia y aconsejaba al virrey", help: "Exacto! Era una pieza clave de la autoridad española y casi todos sus miembros eran peninsulares" },
      distractors: [
        { id: "realista-q13-d1", text: "Era un parlamento elegido por los vecinos", help: "No no, en esa época no se votaban representantes de esa manera" },
        { id: "realista-q13-d2", text: "Era el ejército del virrey", help: "No, el ejército era otra institución" },
        { id: "realista-q13-d3", text: "Era un banco que manejaba los impuestos", help: "No, no se ocupaba de las finanzas" },
        { id: "realista-q13-d4", text: "Era una escuela para los hijos de los funcionarios", help: "No no, nada que ver" },
      ],
    },
    {
      type: "question",
      character: "cisneros",
      speaker: "Baltasar Hidalgo de Cisneros",
      text: "¿Por qué un cabildo abierto es un riesgo para el virrey?",
      background: "fuerte",
      correct: { id: "realista-q14-correct", text: "Porque permite que los vecinos principales discutan y voten, y podrían decidir que el virrey deje de mandar", help: "Exacto! Por eso a mí no me gusta nada la idea" },
      distractors: [
        { id: "realista-q14-d1", text: "Porque es una reunión secreta de espías", help: "No, justamente es una reunión pública" },
        { id: "realista-q14-d2", text: "Porque el virrey está obligado a pagar los gastos", help: "No, no es un problema de dinero" },
        { id: "realista-q14-d3", text: "Porque lo obliga a volver a España", help: "No no, nadie lo obliga a viajar" },
        { id: "realista-q14-d4", text: "No es ningún riesgo, es solo una fiesta", help: "Nooo, es una reunión política muy seria" },
      ],
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "...",
      background: "domingo-20",
    },
    {
      type: "dialogue",
      character: "cisneros",
      speaker: "Baltasar Hidalgo de Cisneros",
      text: "Convoqué a los comandantes militares para saber si puedo contar con las tropas en caso de disturbios",
      background: "fuerte",
    },
    {
      type: "dialogue",
      character: "saavedra",
      speaker: "Cornelio Saavedra",
      text: "Excelencia, con todo respeto: no puedo asegurarle que la tropa lo siga si se la usa contra el pueblo",
      background: "fuerte",
    },
    {
      type: "question",
      character: "cisneros",
      speaker: "Baltasar Hidalgo de Cisneros",
      text: "¿Por qué fue tan grave que los jefes militares no lo respaldaran?",
      background: "fuerte",
      correct: { id: "realista-q18-correct", text: "Porque la principal fuerza de la ciudad eran las milicias criollas formadas tras las invasiones inglesas, y sin ellas casi no tenía cómo imponer su autoridad", help: "Exacto! Desde 1806 y 1807 cuerpos como los Patricios eran la fuerza principal de Buenos Aires" },
      distractors: [
        { id: "realista-q18-d1", text: "Porque no había soldados, solo civiles", help: "No no, había soldados, pero eran en su gran mayoría criollos y no obedecían ciegamente" },
        { id: "realista-q18-d2", text: "Porque todos los soldados eran españoles recién llegados", help: "No, al revés: la mayoría eran de Buenos Aires" },
        { id: "realista-q18-d3", text: "Porque los militares eran los que cobraban los impuestos", help: "No, no era su función" },
        { id: "realista-q18-d4", text: "Porque el ejército se había ido a pelear a Europa", help: "No, el ejército estaba en Buenos Aires" },
      ],
    },
    {
      type: "dialogue",
      character: "cisneros",
      speaker: "Baltasar Hidalgo de Cisneros",
      text: "No me queda alternativa: tendré que aceptar el cabildo abierto. Confío en que los vecinos principales apoyen la autoridad del rey",
      background: "fuerte",
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "...",
      background: "lunes-21",
    },
    {
      type: "dialogue",
      character: "cisneros",
      speaker: "Baltasar Hidalgo de Cisneros",
      text: "La plaza está llena de gente. Hay muchos jóvenes armados que obedecen a Domingo French y a Antonio Beruti",
      background: "fuerte",
    },
    {
      type: "question",
      character: "cisneros",
      speaker: "Baltasar Hidalgo de Cisneros",
      text: "¿Qué apodo les daban sus detractores al grupo de French y Beruti?",
      background: "fuerte",
      correct: { id: "realista-q22-correct", text: "La \"Legión Infernal\"", help: "Sí! Eran jóvenes criollos que movilizaban a la gente humilde a favor del cambio" },
      distractors: [
        { id: "realista-q22-d1", text: "Los Granaderos", help: "No, los Granaderos a caballo se crean recién en 1812" },
        { id: "realista-q22-d2", text: "La Santa Alianza", help: "No, esa alianza europea es de 1815" },
        { id: "realista-q22-d3", text: "Los Tercios de Flandes", help: "No, esos eran los antiguos ejércitos de España" },
        { id: "realista-q22-d4", text: "La Guardia Imperial", help: "No, esa era la guardia de Napoleón" },
      ],
    },
    {
      type: "dialogue",
      character: "cisneros",
      speaker: "Baltasar Hidalgo de Cisneros",
      text: "El Cabildo repartió invitaciones a unos 450 vecinos. Con la plaza así, necesito que mañana nuestra postura se defienda con firmeza",
      background: "fuerte",
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "...",
      background: "martes-22",
    },
    {
      type: "dialogue",
      character: "obispo-lue",
      speaker: "Benito Lué y Riega",
      text: "Excelencia, hoy comienza la sesión. Mi opinión es clara: mientras haya un español en América, los americanos le debemos obediencia",
      background: "cabildo-abierto",
    },
    {
      type: "dialogue",
      character: "villota",
      speaker: "Manuel Genaro de Villota",
      text: "Soy Manuel Genaro de Villota, el fiscal. Yo creo que una sola ciudad no puede decidir por todo el virreinato. Habría que consultar a las demás",
      background: "cabildo-abierto",
    },
    {
      type: "question",
      character: "cisneros",
      speaker: "Baltasar Hidalgo de Cisneros",
      text: "¿Qué argumento usaría usted para defender que Cisneros siga gobernando?",
      background: "cabildo-abierto",
      correct: { id: "realista-q27-correct", text: "Que el virrey es la autoridad del rey y Buenos Aires no puede decidir sola por todo el virreinato", help: "Exacto! Ese fue justamente el argumento más fuerte de los defensores del virrey" },
      distractors: [
        { id: "realista-q27-d1", text: "Que Buenos Aires debe declarar la independencia", help: "Nooo, eso iría contra la autoridad del rey y de la Corona" },
        { id: "realista-q27-d2", text: "Que Napoleón había reconocido al virrey", help: "No, Napoleón era el enemigo de todos acá" },
        { id: "realista-q27-d3", text: "Que los ingleses iban a gobernar el Río de la Plata", help: "No no, nadie planteó eso" },
        { id: "realista-q27-d4", text: "Que el virrey debía convertirse en rey", help: "No, el rey era Fernando VII, aunque estuviera preso" },
      ],
    },
    {
      type: "dialogue",
      character: "paso",
      speaker: "Juan José Paso",
      text: "Respeto al fiscal, pero hay que actuar ya. Buenos Aires puede obrar en nombre de los demás pueblos, y ellos luego aprobarán lo que se decida",
      background: "cabildo-abierto",
    },
    {
      type: "question",
      character: "paso",
      speaker: "Juan José Paso",
      text: "¿Qué respondió Juan José Paso al fiscal Villota?",
      background: "cabildo-abierto",
      correct: { id: "realista-q29-correct", text: "Que Buenos Aires actuara como gestora de los demás pueblos, que luego ratificarían lo decidido", help: "Sí! Esa idea, conocida como \"gestión de negocios\", fue un argumento clave para el bando criollo" },
      distractors: [
        { id: "realista-q29-d1", text: "Que se ignorara a las demás ciudades para siempre", help: "No, justamente propuso que ellas aprobaran después" },
        { id: "realista-q29-d2", text: "Que se declarara la guerra a Montevideo", help: "No, no era un tema de ese día" },
        { id: "realista-q29-d3", text: "Que se pidiera permiso a Napoleón", help: "No no, jamás" },
        { id: "realista-q29-d4", text: "Que se disolviera el Cabildo", help: "No, el Cabildo era el lugar donde se debatía" },
      ],
    },
    {
      type: "dialogue",
      character: "saavedra",
      speaker: "Cornelio Saavedra",
      text: "Mi voto es que Cisneros deje el mando y que el Cabildo gobierne hasta formar una Junta",
      background: "cabildo-abierto",
    },
    {
      type: "dialogue",
      character: "cisneros",
      speaker: "Baltasar Hidalgo de Cisneros",
      text: "El obispo y el fiscal hicieron lo posible. Mañana el Cabildo contará los votos",
      background: "fuerte",
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "...",
      background: "miercoles-23",
    },
    {
      type: "dialogue",
      character: "cisneros",
      speaker: "Baltasar Hidalgo de Cisneros",
      text: "El resultado es adverso: la mayoría votó que yo deje el mando. Pero el Cabildo sigue en manos de muchos peninsulares y aún podemos conservar algo de poder",
      background: "fuerte",
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "...",
      background: "jueves-24",
    },
    {
      type: "question",
      character: "cisneros",
      speaker: "Baltasar Hidalgo de Cisneros",
      text: "¿Cómo intentó el Cabildo conservar el control el 24 de mayo?",
      background: "fuerte",
      correct: { id: "realista-q35-correct", text: "Formó una Junta presidida por el propio virrey Cisneros", help: "Exacto! Cambiaba la forma, pero el virrey seguía mandando" },
      distractors: [
        { id: "realista-q35-d1", text: "Declaró la independencia", help: "Nooo, eso recién es en 1816" },
        { id: "realista-q35-d2", text: "Entregó el poder directamente a Saavedra", help: "No, eso pasó el 25 de mayo" },
        { id: "realista-q35-d3", text: "Mandó a arrestar a French y Beruti", help: "No, no se animaron a tanto" },
        { id: "realista-q35-d4", text: "Pidió ayuda militar a Inglaterra", help: "No no, nada de eso" },
      ],
    },
    {
      type: "dialogue",
      character: "saavedra",
      speaker: "Cornelio Saavedra",
      text: "Excelencia, con dolor se lo digo: ni el pueblo ni la tropa aceptan esta Junta. Castelli y yo renunciamos",
      background: "fuerte",
    },
    {
      type: "dialogue",
      character: "cisneros",
      speaker: "Baltasar Hidalgo de Cisneros",
      text: "La Real Audiencia me aconseja resistir, pero los comandantes no pueden asegurar el orden",
      background: "fuerte",
    },
    {
      type: "question",
      character: "cisneros",
      speaker: "Baltasar Hidalgo de Cisneros",
      text: "¿Qué hizo finalmente Cisneros?",
      background: "fuerte",
      correct: { id: "realista-q38-correct", text: "Aceptó dejar el mando ante la falta de apoyo militar y popular", help: "Exacto! Sin tropas ni apoyo, resistir era imposible" },
      distractors: [
        { id: "realista-q38-d1", text: "Mandó fusilar a los líderes criollos", help: "No no, no tenía fuerzas para eso" },
        { id: "realista-q38-d2", text: "Huyó a Montevideo", help: "No, siguió en Buenos Aires unas semanas más" },
        { id: "realista-q38-d3", text: "Marchó con un ejército a Córdoba", help: "No, no tenía ejército para marchar" },
        { id: "realista-q38-d4", text: "Se proclamó rey", help: "Nooo, solo Fernando VII era el rey" },
      ],
    },
    {
      type: "dialogue",
      character: null,
      speaker: " ",
      text: "...",
      background: "viernes-25",
    },
    {
      type: "dialogue",
      character: "lezica",
      speaker: "Juan José Lezica",
      text: "Excelencia, la plaza está llena de gente bajo la garúa. Llegó un petitorio con cientos de firmas: piden que usted deje el mando y que se forme una nueva Junta",
      background: "cabildo-lleno",
    },
    {
      type: "question",
      character: "lezica",
      speaker: "Juan José Lezica",
      text: "¿Qué hizo el Cabildo ante el petitorio y la presión de la plaza?",
      background: "cabildo-lleno",
      correct: { id: "realista-q41-correct", text: "Aceptó formar una nueva Junta con los nombres propuestos y dejó sin mando a Cisneros", help: "Exacto! Presionado por la plaza y sin apoyo de las tropas, el Cabildo cedió" },
      distractors: [
        { id: "realista-q41-d1", text: "Rechazó todo y mandó disparar a la multitud", help: "No, no tenía fuerzas para hacerlo" },
        { id: "realista-q41-d2", text: "Esperó una orden de la Regencia en Cádiz", help: "No, no había tiempo, el mensaje tardaría meses" },
        { id: "realista-q41-d3", text: "Pidió a Montevideo que enviara barcos de guerra", help: "No, esa no fue su respuesta" },
        { id: "realista-q41-d4", text: "Se disolvió y desapareció", help: "No no, el Cabildo siguió funcionando" },
      ],
    },
    {
      type: "dialogue",
      character: "cisneros",
      speaker: "Baltasar Hidalgo de Cisneros",
      text: "La nueva Junta presidida por Saavedra gobernará en nombre de Fernando VII. Dicen que es una \"máscara\" para ocultar sus verdaderas intenciones",
      background: "fuerte",
    },
    {
      type: "question",
      character: "cisneros",
      speaker: "Baltasar Hidalgo de Cisneros",
      text: "¿Qué significaba gobernar en nombre de Fernando VII?",
      background: "fuerte",
      correct: { id: "realista-q43-correct", text: "Que la Junta no declaraba la independencia sino que gobernaba mientras el rey estuviera preso", help: "Exacto! Algunos desconfiaban, pero oficialmente la ruptura con España todavía no existía" },
      distractors: [
        { id: "realista-q43-d1", text: "Que la Junta le obedecía a la Regencia de Cádiz", help: "No, la Junta no reconocía a la Regencia" },
        { id: "realista-q43-d2", text: "Que la Junta le obedecía a Napoleón", help: "Nooo, era el enemigo" },
        { id: "realista-q43-d3", text: "Que Fernando VII iba a viajar a Buenos Aires", help: "No, estaba preso en Francia" },
        { id: "realista-q43-d4", text: "Que ya se había declarado la independencia", help: "No no, la independencia llegó seis años después" },
      ],
    },
    {
      type: "dialogue",
      character: "cisneros",
      speaker: "Baltasar Hidalgo de Cisneros",
      text: "Esto no termina acá. Montevideo, el Alto Perú y Paraguay no van a aceptar fácilmente a esta Junta",
      background: "fuerte",
    },
    {
      type: "question",
      character: "cisneros",
      speaker: "Baltasar Hidalgo de Cisneros",
      text: "¿Dónde resistieron los realistas después de mayo de 1810?",
      background: "fuerte",
      correct: { id: "realista-q45-correct", text: "En Montevideo, el Alto Perú y Paraguay, entre otros lugares", help: "Exacto! Hubo una larga guerra para decidir el destino de la región" },
      distractors: [
        { id: "realista-q45-d1", text: "En ningún lado, todo el virreinato aceptó a la Junta enseguida", help: "No no, muchas ciudades se negaron a obedecer a Buenos Aires" },
        { id: "realista-q45-d2", text: "Solamente en Buenos Aires", help: "No, justo en Buenos Aires la Junta ganó" },
        { id: "realista-q45-d3", text: "En Brasil, que se unió a España", help: "No, Brasil era una colonia portuguesa y seguía otro camino" },
        { id: "realista-q45-d4", text: "En Francia, donde fue el virrey a pedir ayuda", help: "No, nada de eso" },
      ],
    },
    {
      type: "dialogue",
      character: "cisneros",
      speaker: "Baltasar Hidalgo de Cisneros",
      text: "Pocas semanas después me embarcarán hacia las Islas Canarias junto con los oidores de la Audiencia. Pero recuerde: hasta ahora tanto realistas como patriotas decían obedecer al mismo rey",
      background: "fuerte",
    },
    {
      type: "dialogue",
      character: "cisneros",
      speaker: "Baltasar Hidalgo de Cisneros",
      text: "Gracias por su servicio. Tome esta escarapela como recuerdo ¡Que Dios guarde al rey!",
      background: "fuerte",
    },
  ],
};
